### ISSUE TITLE
PythonFunction can make OT crash

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1090]
The following script makes OT crash
```
import openturns as ot
g = ot.SymbolicFunction(["x"],["x"])
h = ot.PythonFunction(1,1,g)
```

**Comment by mbaudin47** [comment]
This bug is somewhat similar to: http://trac.openturns.org/ticket/792

**Comment by jschueller** [comment]
Stuck in Function::operator==, this is weird pointer passed as 2nd function interface (the "other" arg) is null
```
0x00007ffff5115e0a in OT::Pointer<OT::FunctionImplementation, OT::SharedPointer>::operator bool (this=<optimized out>) at /home/schueller/projects/openturns/schueller/lib/src/Base/Common/openturns/Pointer.hxx:219
219         return ptr_.get() != 0;
(gdb) bt
#0  0x00007ffff5115e0a in OT::Pointer<OT::FunctionImplementation, OT::SharedPointer>::operator bool (this=<optimized out>) at /home/schueller/projects/openturns/schueller/lib/src/Base/Common/openturns/Pointer.hxx:219
#1  OT::Function::operator== (this=0xc721c0, other=...) at /home/schueller/projects/openturns/schueller/lib/src/Base/Func/Function.cxx:95
#2  0x00007fffc3633795 in _wrap_Function___eq__ (args=<optimized out>) at /home/schueller/projects/openturns/schueller/build/python/src/func_modulePYTHON_wrap.cxx:63440
#3  0x0000000000502d6f in ?? ()
#4  0x0000000000506859 in _PyEval_EvalFrameDefault ()
#5  0x0000000000501945 in _PyFunction_FastCallDict ()
#6  0x0000000000591461 in ?? ()
#7  0x00000000005a337c in _PyObject_FastCallDict ()
#8  0x0000000000544d90 in ?? ()
#9  0x00000000005631db in PyObject_RichCompare ()
#10 0x000000000050a808 in _PyEval_EvalFrameDefault ()
#11 0x0000000000504c28 in ?? ()
#12 0x0000000000501ba7 in _PyFunction_FastCallDict ()
#13 0x00000000005a36f1 in _PyObject_FastCallDict ()
#14 0x0000000000544c72 in ?? ()
#15 0x00000000005553b5 in ?? ()
#16 0x00000000005a730c in _PyObject_FastCallKeywords ()
#17 0x0000000000503073 in ?? ()
#18 0x0000000000506859 in _PyEval_EvalFrameDefault ()
#19 0x0000000000504c28 in ?? ()
#20 0x0000000000506393 in PyEval_EvalCode ()
#21 0x0000000000634d52 in ?? ()
#22 0x0000000000634e0a in PyRun_FileExFlags ()
#23 0x00000000006385c8 in PyRun_SimpleFileExFlags ()
#24 0x000000000063915a in Py_Main ()
#25 0x00000000004a6f10 in main ()
```

**Comment by jschueller** [comment]
even shorter:
```
import openturns as ot
ot.Function()==None
```

**Comment by jschueller** [comment]
Problem is operator== does not care about the Interface check typemap, so we cannot check if it is a Py_None.

**Comment by jschueller** [comment]
A work-around is to rewrite None comparison without using the comparision operator.
