### ISSUE TITLE
problem with TensorizedCovarianceModel with spatial dim > 1

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#1254]
It seems I cannot perform a kriging when the kernel is tensorized (sample has 2-d output and kernel has dimension 1), when the spatial dimension is >1 (works with spatial dim 1)

It throws in TensorizedCovarianceModel::setScale at line 210
```
collection_[0].setScale(scale);
```
with scale =[1,0,0]

the message is:
In CovarianceModelImplementation::setScale: the component 1 of scale is non positive

```
from __future__ import print_function
from openturns import *

# Test 1

sampleSize = 6
dimension = 3

f = NumericalMathFunction(['x0', 'x1', 'x2'], ['y']*2, ['x0 * sin(x1)+x2', 'x0 * cos(x1)-x2'])

X = NumericalSample(sampleSize, dimension)
X2 = NumericalSample(sampleSize, dimension)
for i in range(sampleSize):
    X[i, 0] = 3.0 + i
    X2[i, 0] = 2.5 + i
X[0, 0] = 1.0
X[1, 0] = 3.0
X2[0, 0] = 2.0
X2[1, 0] = 4.0
Y = f(X)
Y2 = f(X2)

# create algorithm
basis = ConstantBasisFactory(dimension).build()
covarianceModel = SquaredExponential([1e-05]*dimension, [4.11749])

algo = KrigingAlgorithm(X, Y, basis, covarianceModel)
algo.run()

# perform an evaluation
result = algo.getResult()
print("X=", X)
print("f(X)=", Y)
```
```
#0  0x00007ffff2cf28b0 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff576bf22 in OT::CovarianceModelImplementation::setScale (this=<optimized out>, scale=...) at /home/schueller/projects/openturns/schueller/lib/src/Base/Stat/CovarianceModelImplementation.cxx:526
#2  0x00007ffff57a2fb1 in OT::TensorizedCovarianceModel::setScale (this=0x145ec50, scale=...) at /home/schueller/projects/openturns/schueller/lib/src/Base/Stat/TensorizedCovarianceModel.cxx:211
#3  0x00007ffff57a272f in OT::TensorizedCovarianceModel::setFullParameter (this=<optimized out>, parameter=...) at /home/schueller/projects/openturns/schueller/lib/src/Base/Stat/TensorizedCovarianceModel.cxx:182
#4  0x00007ffff576cfe6 in OT::CovarianceModelImplementation::setParameter (this=<optimized out>, parameter=...) at /home/schueller/projects/openturns/schueller/lib/src/Base/Stat/CovarianceModelImplementation.cxx:652
#5  0x00007ffff5bd34f7 in OT::GeneralizedLinearModelAlgorithm::computeLapackLogDeterminantCholesky (this=0x1446940, parameters=...)
    at /home/schueller/projects/openturns/schueller/lib/src/Uncertainty/Algorithm/MetaModel/Kriging/GeneralizedLinearModelAlgorithm.cxx:621
#6  0x00007ffff5bd0d2e in OT::GeneralizedLinearModelAlgorithm::computeLogLikelihood (this=0x1446940, parameters=...)
    at /home/schueller/projects/openturns/schueller/lib/src/Uncertainty/Algorithm/MetaModel/Kriging/GeneralizedLinearModelAlgorithm.cxx:599
#7  0x00007ffff5bd9a55 in OT::MethodBoundNumericalMathEvaluationImplementation<OT::GeneralizedLinearModelAlgorithm, double, OT::NumericalPoint>::operator() (this=0x1448710, inP=...)
    at /home/schueller/projects/openturns/schueller/lib/src/Base/Func/openturns/MethodBoundNumericalMathEvaluationImplementation.hxx:170
#8  0x00007ffff552f40e in OT::NumericalMathFunctionImplementation::operator() (this=<optimized out>, inP=...) at /home/schueller/projects/openturns/schueller/lib/src/Base/Func/NumericalMathFunctionImplementation.cxx:398
#9  0x00007ffff552bd7e in OT::NumericalMathFunction::operator() (this=<optimized out>, inP=...) at /home/schueller/projects/openturns/schueller/lib/src/Base/Func/NumericalMathFunction.cxx:479
#10 0x00007ffff5bcf7f9 in OT::GeneralizedLinearModelAlgorithm::optimizeLogLikelihood (this=0x1446940)
    at /home/schueller/projects/openturns/schueller/lib/src/Uncertainty/Algorithm/MetaModel/Kriging/GeneralizedLinearModelAlgorithm.cxx:780
#11 0x00007ffff5bcdb42 in OT::GeneralizedLinearModelAlgorithm::run (this=0x1446940) at /home/schueller/projects/openturns/schueller/lib/src/Uncertainty/Algorithm/MetaModel/Kriging/GeneralizedLinearModelAlgorithm.cxx:513
#12 0x00007ffff5bacf5e in OT::KrigingAlgorithm::run (this=0x1446890) at /home/schueller/projects/openturns/schueller/lib/src/Uncertainty/Algorithm/MetaModel/Kriging/KrigingAlgorithm.cxx:183
#13 0x00007fffc2691790 in _wrap_KrigingAlgorithm_run (args=<optimized out>) at /home/schueller/projects/openturns/schueller/build/python/src/metamodel_modulePYTHON_wrap.cxx:27272
#14 0x00000000004e9b9f in PyCFunction_Call ()
#15 0x0000000000524414 in PyEval_EvalFrameEx ()
#16 0x0000000000528814 in PyEval_EvalFrameEx ()
#17 0x000000000052d2e3 in ?? ()
#18 0x000000000052dfdf in PyEval_EvalCode ()
#19 0x00000000005fd2c2 in ?? ()
#20 0x00000000005ff76a in PyRun_FileExFlags ()
#21 0x00000000005ff95c in PyRun_SimpleFileExFlags ()
#22 0x000000000063e7d6 in Py_Main ()
#23 0x00000000004cfe41 in main ()
```
Linked to [http://trac.openturns.org/ticket/870](http://trac.openturns.org/ticket/870)

**Comment by regislebrun** [comment]
Works with current master
