### ISSUE TITLE
ImportFromCSVFile does not manage accents on Windows

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1288]
The following file contains a sample:

[sample_E.txt](https://github.com/openturns/openturns/files/3729807/sample_E.txt)

I saved it into the "Téléchargements" directory. Then the following script fails:
```Python
import openturns as ot
import os
filename = os.path.join(u"Téléchargements","sample_E.txt")
dataE=ot.Sample.ImportFromCSVFile(filename)
```
and generates the following exception:
```bash
Z:>python bug-import.py
Traceback (most recent call last):
  File "bug-import.py", line 13, in <module>
    dataE=ot.Sample.ImportFromCSVFile(filename)
  File "C:\path\anaconda3-2019-03\lib\site-packages\openturns\typ.py", line 7985, in ImportFromCSVFile
    return _typ.Sample_ImportFromCSVFile(*args)
RuntimeError: FileNotFoundException : Can NOT open file 'Téléchargements\sample_E.txt'. Reason: No such file or directory
```

The accents in the directory make OT fail: if I replace "é" by "e", then the script works.

**Comment by sofianehaddad** [comment]
Strange, it works for me on `osx`

**Comment by jschueller** [comment]
ImportFromCSVFile is ok, its a matter how python strings are interpreted in the swig layer, unfortunately we only allow unicode strings, not bytes

**Comment by mbaudin47** [comment]
Ok, so there is nothing that we can do about it at the OT layer. 

But your statement about unicode confuses me: isn't the goal of the "u" in front of `u"Téléchargements"` to specifically state that this is unicode string? Is there a correct way of giving the right filename to `ImportFromCSVFile`?

**Comment by josephmure** [comment]
Hi @mbaudin47 does this still hold? I just tried this out on my Linux laptop and the import works fine.

Your issue may be the "Téléchargements" folder being actually named "Downloads" as far as the shell is concerned: this is how it is on my computer. Even though the file manager shows it as "Téléchargements", its true name is really "Downloads", so I had to manually create a "Téléchargements" folder to reproduce your experiment.

**Comment by mbaudin47** [comment]
Yes, this bug is still alive.

Here is a second example, with a slight difference. The data is in :

[Donnees.csv](https://github.com/openturns/openturns/files/14851585/Donnees.csv)

I consider two versions of the file, with the same content :
- "Données.csv"
- "Donnees.csv"

The script is:
```python
import openturns as ot

sample = ot.Sample.ImportFromCSVFile(r"Données.csv")  # Fails
#sample = ot.Sample.ImportFromCSVFile("Données.csv")  # Fails
#sample = ot.Sample.ImportFromCSVFile(r"Donnees.csv")  # OK
sample
```
Notice that :
- I run the script on Windows,
- I tried different flavours of strings, using accents or not, or using a _raw string_ (see [What exactly do "u" and "r" string](https://stackoverflow.com/questions/2081640/what-exactly-do-u-and-r-string-prefixes-do-and-what-are-raw-string-literals).

When the script fails, the error is:
```
RuntimeError: FileNotFoundException : Can NOT open file 'Données.csv'. 
Reason: No such file or directory
```
I guess that the fact that the Python script runs on Windows is an important part of the issue. This is why I update the title. 

A workaround is to use Pandas's `read_csv` as shown in the next script.
```
import pandas as pd
data = pd.read_csv("Données.csv")  # OK
#data = pd.read_csv(r"Données.csv")  # OK
data
```
