### ISSUE TITLE
Rosenblatt transformation segfault

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#1303]
Using the following script:
```
import openturns as ot

size = 100000
copula = ot.FrankCopula(5.0)
transformation = copula.getIsoProbabilisticTransformation()
sample = copula.getSample(size)
result = transformation(sample)
```
I get a segmentation fault with the current master (compiled with or without TBB) or with OT 1.13, but everything is ok with `size=10000`

**Comment by jschueller** [comment]
confirmed, looks like a FrankCopula pointer references itself somewhere in the transfo:
```
#0  0x00007ffff547bc75 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x29e4e00) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/shared_ptr_base.h:154
#1  std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/shared_ptr_base.h:684
#2  std::__shared_ptr<OT::EvaluationImplementation, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/shared_ptr_base.h:1123
#3  OT::Pointer<OT::EvaluationImplementation, std::shared_ptr>::~Pointer (this=<optimized out>) at /home/schueller/projects/openturns/schueller2/lib/src/Base/Common/openturns/Pointer.hxx:102
#4  OT::DistributionImplementation::~DistributionImplementation (this=0x29e5d50) at /home/schueller/projects/openturns/schueller2/lib/src/Uncertainty/Model/openturns/DistributionImplementation.hxx:55
#5  0x00007ffff568ea39 in OT::FrankCopula::~FrankCopula (this=0x29e5d50) at /home/schueller/projects/openturns/schueller2/lib/src/Uncertainty/Distribution/openturns/FrankCopula.hxx:33
#6  0x00007ffff5549957 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x29e55a0) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/shared_ptr_base.h:154
#7  std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x29e5be8) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/shared_ptr_base.h:684
#8  std::__shared_ptr<OT::DistributionImplementation, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x29e5be0) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/shared_ptr_base.h:1123
#9  OT::Pointer<OT::DistributionImplementation, std::shared_ptr>::~Pointer (this=0x29e5be0) at /home/schueller/projects/openturns/schueller2/lib/src/Base/Common/openturns/Pointer.hxx:102
#10 OT::ConditionalPDFWrapper::~ConditionalPDFWrapper (this=0x29e5a20) at /home/schueller/projects/openturns/schueller2/lib/src/Uncertainty/Model/DistributionImplementation.cxx:84
#11 OT::ConditionalPDFWrapper::~ConditionalPDFWrapper (this=0x29e5a20) at /home/schueller/projects/openturns/schueller2/lib/src/Uncertainty/Model/DistributionImplementation.cxx:84
#12 0x00007ffff547bc78 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x29e5540) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/shared_ptr_base.h:154
#13 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/shared_ptr_base.h:684
#14 std::__shared_ptr<OT::EvaluationImplementation, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/shared_ptr_base.h:1123
#15 OT::Pointer<OT::EvaluationImplementation, std::shared_ptr>::~Pointer (this=<optimized out>) at /home/schueller/projects/openturns/schueller2/lib/src/Base/Common/openturns/Pointer.hxx:102
#16 OT::DistributionImplementation::~DistributionImplementation (this=0x29e6490) at /home/schueller/projects/openturns/schueller2/lib/src/Uncertainty/Model/openturns/DistributionImplementation.hxx:55
#17 0x00007ffff568ea39 in OT::FrankCopula::~FrankCopula (this=0x29e6490) at /home/schueller/projects/openturns/schueller2/lib/src/Uncertainty/Distribution/openturns/FrankCopula.hxx:33
#18 0x00007ffff5549957 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x29e5ce0) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/shared_ptr_base.h:154
#19 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x29e6328) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/shared_ptr_base.h:684
#20 std::__shared_ptr<OT::DistributionImplementation, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x29e6320) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/shared_ptr_base.h:1123
#21 OT::Pointer<OT::DistributionImplementation, std::shared_ptr>::~Pointer (this=0x29e6320) at /home/schueller/projects/openturns/schueller2/lib/src/Base/Common/openturns/Pointer.hxx:102
#22 OT::ConditionalPDFWrapper::~ConditionalPDFWrapper (this=0x29e6160) at /home/schueller/projects/openturns/schueller2/lib/src/Uncertainty/Model/DistributionImplementation.cxx:84
#23 OT::ConditionalPDFWrapper::~ConditionalPDFWrapper (this=0x29e6160) at /home/schueller/projects/openturns/schueller2/lib/src/Uncertainty/Model/DistributionImplementation.cxx:84
#24 0x00007ffff547bc78 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x29e3f00) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/shared_ptr_base.h:154
#25 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/shared_ptr_base.h:684
#26 std::__shared_ptr<OT::EvaluationImplementation, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/shared_ptr_base.h:1123
#27 OT::Pointer<OT::EvaluationImplementation, std::shared_ptr>::~Pointer (this=<optimized out>) at /home/schueller/projects/openturns/schueller2/lib/src/Base/Common/openturns/Pointer.hxx:102
#28 OT::DistributionImplementation::~DistributionImplementation (this=0x29e6bd0) at /home/schueller/projects/openturns/schueller2/lib/src/Uncertainty/Model/openturns/DistributionImplementation.hxx:55
#29 0x00007ffff568ea39 in OT::FrankCopula::~FrankCopula (this=0x29e6bd0) at /home/schueller/projects/openturns/schueller2/lib/src/Uncertainty/Distribution/openturns/FrankCopula.hxx:33
#30 0x00007ffff5549957 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x29e6420) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/shared_ptr_base.h:154
#31 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x29e6a68) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/shared_ptr_base.h:684
#32 std::__shared_ptr<OT::DistributionImplementation, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x29e6a60) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/shared_ptr_base.h:1123
#33 OT::Pointer<OT::DistributionImplementation, std::shared_ptr>::~Pointer (this=0x29e6a60) at /home/schueller/projects/openturns/schueller2/lib/src/Base/Common/openturns/Pointer.hxx:102
#34 OT::ConditionalPDFWrapper::~ConditionalPDFWrapper (this=0x29e68a0) at /home/schueller/projects/openturns/schueller2/lib/src/Uncertainty/Model/DistributionImplementation.cxx:84
#35 OT::ConditionalPDFWrapper::~ConditionalPDFWrapper (this=0x29e68a0) at /home/schueller/projects/openturns/schueller2/lib/src/Uncertainty/Model/DistributionImplementation.cxx:84
#36 0x00007ffff547bc78 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x29e63c0) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/shared_ptr_base.h:154
#37 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/shared_ptr_base.h:684
```
