### ISSUE TITLE
GeneralLinearModelAlgorithm::computeReducedLogLikelihood code question

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1328]
I am not sure what [this line](https://github.com/josephmure/openturns/blob/0ae3e83643240ddac3d7e3fe9dbe0ff9485c8103/lib/src/Uncertainty/Algorithm/MetaModel/Kriging/GeneralLinearModelAlgorithm.cxx#L748) is supposed to do.
The block of code immediately above is:

```
  const Scalar epsilon = rho_.normSquare();
  LOGDEBUG(OSS(false) << "epsilon=||rho||^2=" << epsilon);

  if (epsilon <= 0) lastReducedLogLikelihood_ = SpecFunc::LogMinScalar;
```
It seems to me that epsilon is necessarily >=0 due to its construction as the square of a norm. 
Could epsilon be 0? Because the covariance matrix is positive definite, that would imply that $y - F \beta$ is null. Is that not checked somewhere else? That feels like something the user should be warned about.

Here is a simple example where there exists $\beta$ such that $y = F \beta$:

```
import openturns as ot
sampleX = [[1.0], [2.0], [3.0], [4.0], [5.0], [6.0], [7.0], [8.0]]
sampleY = [[1.0], [1.0], [1.0], [1.0], [1.0], [1.0], [1.0], [1.0]]

basis = ot.ConstantBasisFactory(1).build()
covarianceModel = ot.SquaredExponential([1.0])
algo = ot.KrigingAlgorithm(sampleX, sampleY, covarianceModel, basis)
algo.run()
```
The last line, ``algo.run()`` produces the following warnings:
```
WRN - Switch to finite difference to compute the gradient at point=class=Point name=Unnamed dimension=1 values=[2.00066]
WRN - Warning! TNC algorithm failed to converge. The error message is User requested end of minimization
```
This is to be expected since this example was designed to result in a null $y - F \hat{\beta}$.

Now let us compute the reduced log-likelihood at several points:
`rll = algo.getReducedLogLikelihoodFunction()`

`rll([0.1])` produces an error:
```
Traceback (most recent call last):

  File "<ipython-input-35-555d5b56cca2>", line 1, in <module>
    rll([0.1])

  File "/home/C39575/anaconda3/lib/python3.7/site-packages/openturns/func.py", line 10003, in __call__
    return _func.Function___call__(self, *args)

TypeError: InvalidArgumentException : In CovarianceModelImplementation::setAmplitude, the component 0 of amplitude is non positive
```

On the other hand, the reduced log likelihood can be evaluated at other points:

```
print(rll([0.5]))
[285.259]

print(rll([1.0]))
[298.123]

print(rll([2.0]))
[315.479]
```

I do not understand how these values are computed. Mathematically speaking, the reduced likelihood should not even be properly defined in such a case.

**Comment by regislebrun** [comment]
Here are some elements:
+ epsilon can be zero if rho_ is zero
+ epsilon can be NaN if rho_ contains NaNs
The test allows to deal with both cases in one shot

**Comment by josephmure** [comment]
>     * epsilon can be NaN if rho_ contains NaNs
@regislebrun  do you mean that if epsilon is NaN, then `epsilon<=0` is true?

**Comment by josephmure** [comment]
@mbaudin47 This issue is generally still relevant, because this code was simply moved to GaussianProcessFitter.
