### ISSUE TITLE
The optional Ipopt requirements prevents the Sphinx doc from building

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1413]
I build OpenTURNS without the Ipopt install:
```
-- The following OPTIONAL packages have not been found:

 * Spectra
 * HMAT (required version >= 1.6)
 * Ipopt
```

This is not an issue, since Ipopt is not mandatory. 

However, the build fails because the Sphinx doc does not find the Ipopt symbols:

```
ImportError: /home/osboxes/GIT/openturns-FixDoc/openturns/build/python/src/_optim.so: undefined symbol: _ZTVN2OT5IpoptE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3/dist-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension execforresourcemap_directive (exception: /home/osboxes/GIT/openturns-FixDoc/openturns/build/python/src/_optim.so: undefined symbol: _ZTVN2OT5IpoptE)

Extension error:
Could not import extension execforresourcemap_directive (exception: /home/osboxes/GIT/openturns-FixDoc/openturns/build/python/src/_optim.so: undefined symbol: _ZTVN2OT5IpoptE)
make[2]: *** [python/src/CMakeFiles/sphinx_html.dir/build.make:628: python/src/CMakeFiles/sphinx_html] Error 2
make[1]: *** [CMakeFiles/Makefile2:39038: python/src/CMakeFiles/sphinx_html.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

**Comment by jschueller** [comment]
I cannot reproduce, could you retry to build from scratch ?

**Comment by mbaudin47** [comment]
I cannot neither : I guess it I should have restarted from scratch. This is why I close the bug.
