### ISSUE TITLE
ComparisonOperator().getImplementation().getClassName() segfault

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#1461]
Hi,
The getClassName() is used for introspection, but makes Python crash as the following example shows:
```
import openturns as ot
print(ot.ComparisonOperator(ot.Greater()).getImplementation().getClassName())
```
Using gdb I get:
```
[regis@localhost openturns-adm (master)]$ gdb python3
GNU gdb (GDB) 8.2-8.mga7 (Mageia release 7)
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-mageia-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...Reading symbols from .gnu_debugdata for /usr/bin/python3.7m...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Missing separate debuginfos, use: debuginfo-install python3-3.7.6-1.mga7.x86_64
(gdb) run bug.py
Starting program: /usr/bin/python3 bug.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff0f6d700 (LWP 16192)]
[New Thread 0x7fffee76c700 (LWP 16193)]
[New Thread 0x7fffebf6b700 (LWP 16194)]
[New Thread 0x7fffe976a700 (LWP 16195)]
[New Thread 0x7fffe6f69700 (LWP 16196)]
[New Thread 0x7fffe4768700 (LWP 16197)]
[New Thread 0x7fffe1f67700 (LWP 16198)]

Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007ffff6a963a1 in _wrap_ComparisonOperatorImplementationPointer_getClassName () from /home/regis/openturns-adm/build/install/lib64/python3.7/site-packages/openturns/_common.so
(gdb) bt
#0  0x00007ffff6a963a1 in _wrap_ComparisonOperatorImplementationPointer_getClassName () from /home/regis/openturns-adm/build/install/lib64/python3.7/site-packages/openturns/_common.so
#1  0x00007ffff7b55a29 in _PyMethodDef_RawFastCallKeywords () from /lib64/libpython3.7m.so.1.0
#2  0x00007ffff7b55ae5 in _PyCFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#3  0x00007ffff7af2830 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#4  0x00007ffff7aeb5f3 in function_code_fastcall () from /lib64/libpython3.7m.so.1.0
#5  0x00007ffff7af25cd in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#6  0x00007ffff7b9eb3e in _PyEval_EvalCodeWithName () from /lib64/libpython3.7m.so.1.0
#7  0x00007ffff7b9edae in PyEval_EvalCodeEx () from /lib64/libpython3.7m.so.1.0
#8  0x00007ffff7b9eddb in PyEval_EvalCode () from /lib64/libpython3.7m.so.1.0
#9  0x00007ffff7c3e394 in run_mod () from /lib64/libpython3.7m.so.1.0
#10 0x00007ffff7c3ee41 in PyRun_FileExFlags () from /lib64/libpython3.7m.so.1.0
#11 0x00007ffff7c5b01d in PyRun_SimpleFileExFlags () from /lib64/libpython3.7m.so.1.0
#12 0x00007ffff7c5f4b2 in pymain_main () from /lib64/libpython3.7m.so.1.0
#13 0x00007ffff7c5f729 in _Py_UnixMain () from /lib64/libpython3.7m.so.1.0
#14 0x00007ffff7db4b0b in __libc_start_main () from /lib64/libc.so.6
#15 0x000000000040107a in _start ()
```
It makes penstock fails...

**Comment by jschueller** [comment]
finally cracked it!
