### ISSUE TITLE
Change in Ipopt librairy breaks OT

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#1611]
Using Ipopt version 3.13.2 leads to the following error when executing t_Ipopt_std.py:
```
172/786 Testing: pyinstallcheck_Ipopt_std
172/786 Test: pyinstallcheck_Ipopt_std
Command: "/usr/bin/sh" "-c" "(/usr/bin/python3 /home/regis/openturns-dev/python/test/t_Ipopt_std.py  > /dev/null)"
Directory: /home/regis/openturns-dev/build_various_fixes/python/test
"pyinstallcheck_Ipopt_std" start time: Oct 09 10:02 CEST
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/regis/openturns-dev/python/test/t_Ipopt_std.py", line 45, in <module>
    algo.run()
  File "/home/regis/openturns-dev/build_various_fixes/install/lib64/python3.8/site-packages/openturns/optim.py", line 3988, in run
    return _optim.Ipopt_run(self)
RuntimeError: InternalException : Ipopt error: Invalid option
<end of output>
Test time =   0.26 sec
----------------------------------------------------------
Test Failed.
"pyinstallcheck_Ipopt_std" end time: Oct 09 10:02 CEST
"pyinstallcheck_Ipopt_std" time elapsed: 00:00:00
```

**Comment by jschueller** [comment]
that's the version we're currently using in circleci, do you mean master ?

**Comment by jschueller** [comment]
metis & mumps are correctly installed ?

**Comment by regislebrun** [comment]
I installed Ipopt using coinbrew (https://github.com/coin-or/coinbrew), it is supposed to ease the compilation of coinOR components! I selected the latest stable release of Ipopt, and a look at IpoptConfig.h confirms that it is the 3.13.2 version.
My general feeling is that getting a working installation of coinOR is a real pain, I was not able to get Bonmin working using coinbrew because the compilation fails on one of its dependency. Maybe a step-by step procedure should be written in our documentation? I started one such document for myself, but I get stuck on Bonmin...

**Comment by jschueller** [comment]
you can look at my scripts:
https://github.com/openturns/docker-images/blob/master/manylinux1_x86_64/Dockerfile#L25

**Comment by regislebrun** [comment]
No luck yesterday and today: www.coin-or.org is down so no Bonmin, and I get errors when compiling Mumps:
```
 gfortran -I. -I. -I./MUMPS/src -I./MUMPS/libseq -I./MUMPS/include -O3 -pipe -Dmetis -c MUMPS/src/tools_common_mod.F  -fPIC -o .libs/tools_common_mod.o
/bin/sh ./libtool --tag=F77 --mode=compile gfortran  -I. -I`echo .`  -I`echo ./MUMPS/src` -I`echo ./MUMPS/libseq` -I`echo ./MUMPS/include`   -O3 -pipe   -Dmetis -c -o dmumps_comm_buffer.lo `test -f 'MUMPS/src/dmumps_comm_buffer.F' || echo './'`MUMPS/src/dmumps_comm_buffer.F
 gfortran -I. -I. -I./MUMPS/src -I./MUMPS/libseq -I./MUMPS/include -O3 -pipe -Dmetis -c MUMPS/src/dmumps_comm_buffer.F  -fPIC -o .libs/dmumps_comm_buffer.o
MUMPS/src/dmumps_comm_buffer.F:2667:23:

 2658 |         CALL MPI_PACK( WHAT, 1, MPI_INTEGER,
      |                       2
......
 2667 |         CALL MPI_PACK( LIST_SLAVES, NSLAVES, MPI_INTEGER,
      |                       1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
MUMPS/src/dmumps_comm_buffer.F:2670:23:

 2658 |         CALL MPI_PACK( WHAT, 1, MPI_INTEGER,
      |                       2
......
 2670 |         CALL MPI_PACK( FLOPS_INCREMENT, NSLAVES,
      |                       1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/INTEGER(4)).
MUMPS/src/dmumps_comm_buffer.F:2675:25:

 2658 |         CALL MPI_PACK( WHAT, 1, MPI_INTEGER,
      |                       2  
......
 2675 |           CALL MPI_PACK( MEM_INCREMENT, NSLAVES,
      |                         1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/INTEGER(4)).
MUMPS/src/dmumps_comm_buffer.F:2681:26:
...
```
so no Ipopt either... When I say its a pain in the ass...

**Comment by jschueller** [comment]
that's related to gcc 10, try adding the -fallow-argument-mismatch compilation flag, look for OPTF in Makefile

**Comment by regislebrun** [comment]
You may have to upgrade your configuration file, because coin-or.org seems to be down!
![coin-or-down](https://user-images.githubusercontent.com/8220933/95662873-5b239780-0b3a-11eb-9dfd-d66422cf39ba.png)

**Comment by jschueller** [comment]
my scripts only has to work on wednesday nights :)
