### ISSUE TITLE
Cannot load conda-installed OpenTURNS 1.17

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1860]
Steps to reproduce on Debian 9 : 

```
conda create --name ot117
conda activate ot117
conda install -c conda-forge openturns
python
>>> import openturns
```
This produces the following error message:

```
Python 3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:13:33) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openturns as ot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "miniconda3test/envs/ot117/lib/python3.9/site-packages/openturns/__init__.py", line 61, in <module>
    from .common import *
  File "miniconda3test/envs/ot117/lib/python3.9/site-packages/openturns/common.py", line 15, in <module>
    from . import _common
ImportError: libipopt.so.1: cannot open shared object file: No such file or directory
```

**Comment by JPelamatti** [comment]
I confirm having the same issue as @josephmure .
It is also interesting to notice that I have another conda environment onto which I installed openturns 1.17 a couple of weeks after the releasem for which this issue does not appear.

**Comment by jschueller** [comment]
the instrutions you give suggest you're not using the good repo settings, did you try the instructions from the doc ?

**Comment by vchabri** [comment]
Hi all,
I tried the commands proposed here `https://openturns.github.io/openturns/latest/install.html`, but it does not work on my computer.
I assume it is an inner "EDF-proxy-style" problem, but I put it there for your interest and expertise.
`(base) XXXX@mymachine:~$ conda install -y openturns
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/linux-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://conda.anaconda.org/conda-forge/linux-64'
`
BTW, I don't get the link between the miniforge installation and the conda installation. On my computer, I installed miniconda3, then I followed the official commands. Do I need to parametrize miniconda wrt the installation of miniforge?

**Comment by jschueller** [comment]
yes, conda-forge needs to have top priority

**Comment by josephmure** [comment]
Hi @vchabri! I think the HTTP error is unrelated. I did not encounter it following the doc instructions @jschueller pointed to. However, using Miniforge does not solve the issue: I get exactly the same error. Here is the output of `conda list` I get with a fresh Miniforge + openturns install:

```
$ conda list
# packages in environment at miniforge:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
ampl-mp                   3.1.0             h616b090_1004    conda-forge
brotlipy                  0.7.0           py39h3811e60_1001    conda-forge
c-ares                    1.17.1               h7f98852_1    conda-forge
ca-certificates           2021.5.30            ha878542_0    conda-forge
ceres-solver              2.0.0                h1a78537_2    conda-forge
certifi                   2021.5.30        py39hf3d152e_0    conda-forge
cffi                      1.14.5           py39he32792d_0    conda-forge
chardet                   4.0.0            py39hf3d152e_1    conda-forge
cminpack                  1.3.8                h1c10d02_0    conda-forge
coinbonmin                1.8.8                h2048f75_0    conda-forge
coincbc                   2.10.5               hcee13e7_1    conda-forge
conda                     4.10.1           py39hf3d152e_0    conda-forge
conda-package-handling    1.7.3            py39h3811e60_0    conda-forge
cryptography              3.4.7            py39hbca0aa6_0    conda-forge
dill                      0.3.4              pyhd8ed1ab_0    conda-forge
dlib-cpp                  19.22                he5c009d_0    conda-forge
eigen                     3.3.9                h4bd325d_1    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
glog                      0.5.0                h48cff8f_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
hmat-oss                  1.6.1                h5171369_0    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
ipopt                     3.14.0               h7ede334_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
krb5                      1.19.1               hcc1bbae_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                9_openblas    conda-forge
libcblas                  3.9.0                9_openblas    conda-forge
libcurl                   7.77.0               h2574ce0_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgfortran-ng            9.3.0               hff62375_19    conda-forge
libgfortran5              9.3.0               hff62375_19    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                9_openblas    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libopenblas               0.3.15          pthreads_h8fe5266_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
metis                     5.1.0             h58526e2_1006    conda-forge
mpc                       1.1.0             h04dde30_1009    conda-forge
mpfr                      4.0.2                he80fd80_1    conda-forge
mumps-include             5.2.1               ha770c72_10    conda-forge
mumps-seq                 5.2.1               h47a8eb5_10    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nlopt                     2.7.0            py39hf3b21e1_0    conda-forge
numpy                     1.20.3           py39hdbf815f_1    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
openturns                 1.17             py39hb0d7c36_0    conda-forge
pip                       21.1.2             pyhd8ed1ab_0    conda-forge
psutil                    5.8.0            py39h3811e60_1    conda-forge
pycosat                   0.6.3           py39h3811e60_1006    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39hf3d152e_3    conda-forge
python                    3.9.5           h49503c6_0_cpython    conda-forge
python_abi                3.9                      1_cp39    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
ruamel_yaml               0.15.80         py39h3811e60_1004    conda-forge
scotch                    6.0.9                h0eec0ba_1    conda-forge
setuptools                49.6.0           py39hf3d152e_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.35.5               h74cdb3f_0    conda-forge
suitesparse               5.7.2                h7a0d4b7_0    conda-forge
tbb                       2020.2               h4bd325d_4    conda-forge
tbb-devel                 2020.2               h4bd325d_4    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tqdm                      4.61.1             pyhd8ed1ab_0    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
urllib3                   1.26.5             pyhd8ed1ab_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
```

**Comment by jschueller** [comment]
I dont see anything wrong: ipopt is at 3.14.0 and this version provides libipopt.so.3, something else must interfere

**Comment by josephmure** [comment]
libipopt.so.3 is in miniforge/lib, but libipopt.so.1 was missing from the system. I fixed this via

`` sudo apt install coinor-libipopt-dev``

But now I have another missing dependency !

```
>>> import openturns
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/C39575/miniforge/lib/python3.9/site-packages/openturns/__init__.py", line 61, in <module>
    from .common import *
  File "/home/C39575/miniforge/lib/python3.9/site-packages/openturns/common.py", line 15, in <module>
    from . import _common
ImportError: libgfortran.so.4: cannot open shared object file: No such file or directory
```
I do have `libgfortran.so.3` on my system, but there is no trace of `libgfortran.so.4`

**Comment by jschueller** [comment]
dont install libipopt.so.1 that's worse, instead we should figure out which lib tries to incorrectly load it instead of libipopt.so.3

**Comment by jschueller** [comment]
it looks like its some dependency that requires libipopt.so.1, could you run ldd on `~/miniforge/lib/*.so` ?

**Comment by josephmure** [comment]
Here are the parts of the output that mention `libipopt.so.1`:

```
~/miniforge/lib/libbonminampl.so:
	linux-vdso.so.1 (0x00007fffb836a000)
	libbonmin.so.4 => ~/miniforge/lib/./libbonmin.so.4 (0x00007f5f3fa95000)
	libCbcSolver.so.3 => ~/miniforge/lib/./libCbcSolver.so.3 (0x00007f5f3f89b000)
	libCbc.so.3 => ~/miniforge/lib/./libCbc.so.3 (0x00007f5f3f776000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5f3f559000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5f3f351000)
	libCgl.so.1 => ~/miniforge/lib/./libCgl.so.1 (0x00007f5f3f237000)
	libOsiClp.so.1 => ~/miniforge/lib/./libOsiClp.so.1 (0x00007f5f3f9fe000)
	libClpSolver.so.1 => ~/miniforge/lib/./libClpSolver.so.1 (0x00007f5f3f1cb000)
	libClp.so.1 => ~/miniforge/lib/./libClp.so.1 (0x00007f5f3effc000)
	libOsi.so.1 => ~/miniforge/lib/./libOsi.so.1 (0x00007f5f3efa4000)
	libCoinUtils.so.3 => ~/miniforge/lib/./libCoinUtils.so.3 (0x00007f5f3ee64000)
	libipoptamplinterface.so.1 => not found
	libasl.so.3 => ~/miniforge/lib/./libasl.so.3 (0x00007f5f3ed9b000)
	libipopt.so.1 => not found
	libdmumps_seq-5.2.1.so => ~/miniforge/lib/./libdmumps_seq-5.2.1.so (0x00007f5f3eb75000)
	libmumps_common_seq-5.2.1.so => ~/miniforge/lib/./libmumps_common_seq-5.2.1.so (0x00007f5f3eb14000)
	libpord_seq-5.2.1.so => ~/miniforge/lib/./libpord_seq-5.2.1.so (0x00007f5f3f9e3000)
	libmpiseq_seq-5.2.1.so => ~/miniforge/lib/./libmpiseq_seq-5.2.1.so (0x00007f5f3f9d5000)
	libesmumps-6.so => ~/miniforge/lib/./libesmumps-6.so (0x00007f5f3f9ce000)
	libscotch-6.so => ~/miniforge/lib/./libscotch-6.so (0x00007f5f3ea6f000)
	libscotcherr-6.so => ~/miniforge/lib/./libscotcherr-6.so (0x00007f5f3f9c9000)
	libmetis.so => ~/miniforge/lib/./libmetis.so (0x00007f5f3e9fa000)
	libgfortran.so.4 => not found
	liblapack.so.3 => ~/miniforge/lib/./liblapack.so.3 (0x00007f5f3c9d6000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5f3c7d2000)
	libstdc++.so.6 => ~/miniforge/lib/./libstdc++.so.6 (0x00007f5f3c65d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5f3c359000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5f3bfba000)
	libgcc_s.so.1 => ~/miniforge/lib/./libgcc_s.so.1 (0x00007f5f3bfa6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5f3f99f000)
	libipopt.so.1 => not found
	libgfortran.so.4 => not found
	libmp.so.3 => ~/miniforge/lib/././libmp.so.3 (0x00007f5f3bf5c000)
	libgfortran.so.5 => ~/miniforge/lib/././libgfortran.so.5 (0x00007f5f3bdbc000)
	libgomp.so.1 => ~/miniforge/lib/././libgomp.so.1 (0x00007f5f3bd8f000)
	libz.so.1 => ~/miniforge/lib/././libz.so.1 (0x00007f5f3bd75000)
	libquadmath.so.0 => ~/miniforge/lib/././libquadmath.so.0 (0x00007f5f3bd3b000)
~/miniforge/lib/libbonmin.so:
	linux-vdso.so.1 (0x00007ffcc2e5d000)
	libCbcSolver.so.3 => ~/miniforge/lib/./libCbcSolver.so.3 (0x00007ff601a38000)
	libCbc.so.3 => ~/miniforge/lib/./libCbc.so.3 (0x00007ff601913000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff6016f6000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ff6014ee000)
	libCgl.so.1 => ~/miniforge/lib/./libCgl.so.1 (0x00007ff6013d4000)
	libOsiClp.so.1 => ~/miniforge/lib/./libOsiClp.so.1 (0x00007ff601bc1000)
	libClpSolver.so.1 => ~/miniforge/lib/./libClpSolver.so.1 (0x00007ff601368000)
	libClp.so.1 => ~/miniforge/lib/./libClp.so.1 (0x00007ff601199000)
	libOsi.so.1 => ~/miniforge/lib/./libOsi.so.1 (0x00007ff601b69000)
	libCoinUtils.so.3 => ~/miniforge/lib/./libCoinUtils.so.3 (0x00007ff601059000)
	libipopt.so.1 => not found
	libdmumps_seq-5.2.1.so => ~/miniforge/lib/./libdmumps_seq-5.2.1.so (0x00007ff600e33000)
	libmumps_common_seq-5.2.1.so => ~/miniforge/lib/./libmumps_common_seq-5.2.1.so (0x00007ff600dd2000)
	libpord_seq-5.2.1.so => ~/miniforge/lib/./libpord_seq-5.2.1.so (0x00007ff600db9000)
	libmpiseq_seq-5.2.1.so => ~/miniforge/lib/./libmpiseq_seq-5.2.1.so (0x00007ff600dad000)
	libesmumps-6.so => ~/miniforge/lib/./libesmumps-6.so (0x00007ff601b60000)
	libscotch-6.so => ~/miniforge/lib/./libscotch-6.so (0x00007ff600d08000)
	libscotcherr-6.so => ~/miniforge/lib/./libscotcherr-6.so (0x00007ff600d01000)
	libmetis.so => ~/miniforge/lib/./libmetis.so (0x00007ff600c8c000)
	libgfortran.so.4 => not found
	liblapack.so.3 => ~/miniforge/lib/./liblapack.so.3 (0x00007ff5fec68000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff5fea64000)
	libstdc++.so.6 => ~/miniforge/lib/./libstdc++.so.6 (0x00007ff5fe8ef000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff5fe5e9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff5fe24a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff601b3c000)
	libgcc_s.so.1 => ~/miniforge/lib/./libgcc_s.so.1 (0x00007ff5fe236000)
	libgfortran.so.5 => ~/miniforge/lib/././libgfortran.so.5 (0x00007ff5fe096000)
	libgomp.so.1 => ~/miniforge/lib/././libgomp.so.1 (0x00007ff5fe069000)
	libz.so.1 => ~/miniforge/lib/././libz.so.1 (0x00007ff5fe04d000)
	libquadmath.so.0 => ~/miniforge/lib/././libquadmath.so.0 (0x00007ff5fe013000)

~/miniforge/lib/libOT.so:
	linux-vdso.so.1 (0x00007fff7afba000)
	libtbb.so.2 => ~/miniforge/lib/./libtbb.so.2 (0x00007f4ad0f71000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4acf43d000)
	liblapack.so.3 => ~/miniforge/lib/./liblapack.so.3 (0x00007f4acd419000)
	libhmat-oss.so.1 => ~/miniforge/lib/./libhmat-oss.so.1 (0x00007f4ad0df1000)
	libxml2.so.2 => ~/miniforge/lib/./libxml2.so.2 (0x00007f4acd2b1000)
	libhdf5_cpp.so.103 => ~/miniforge/lib/./libhdf5_cpp.so.103 (0x00007f4acd233000)
	libhdf5.so.103 => ~/miniforge/lib/./libhdf5.so.103 (0x00007f4acceaa000)
	libmpfr.so.6 => ~/miniforge/lib/./libmpfr.so.6 (0x00007f4acce2b000)
	libmpc.so.3 => ~/miniforge/lib/./libmpc.so.3 (0x00007f4ad0dd4000)
	libnlopt.so.0 => ~/miniforge/lib/./libnlopt.so.0 (0x00007f4accd84000)
	libdlib.so.19.22.0 => ~/miniforge/lib/./libdlib.so.19.22.0 (0x00007f4accb9c000)
	libceres.so.2 => ~/miniforge/lib/./libceres.so.2 (0x00007f4acc8fe000)
	libcminpack.so.1 => ~/miniforge/lib/./libcminpack.so.1 (0x00007f4ad0db2000)
	libbonmin.so.4 => ~/miniforge/lib/./libbonmin.so.4 (0x00007f4acc7f9000)
	libipopt.so.3 => ~/miniforge/lib/./libipopt.so.3 (0x00007f4acc57c000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4acc378000)
	libglog.so.0 => ~/miniforge/lib/./libglog.so.0 (0x00007f4acc340000)
	libgflags.so.2.2 => ~/miniforge/lib/./libgflags.so.2.2 (0x00007f4acc31b000)
	libstdc++.so.6 => ~/miniforge/lib/./libstdc++.so.6 (0x00007f4acc1a6000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4acbea2000)
	libgomp.so.1 => ~/miniforge/lib/./libgomp.so.1 (0x00007f4acbe75000)
	libgcc_s.so.1 => ~/miniforge/lib/./libgcc_s.so.1 (0x00007f4acbe61000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4acbac2000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f4acb8ba000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4ad0d84000)
	libgfortran.so.5 => ~/miniforge/lib/././libgfortran.so.5 (0x00007f4acb71a000)
	libicuuc.so.68 => ~/miniforge/lib/././libicuuc.so.68 (0x00007f4acb530000)
	libz.so.1 => ~/miniforge/lib/././libz.so.1 (0x00007f4acb516000)
	liblzma.so.5 => ~/miniforge/lib/././liblzma.so.5 (0x00007f4acb4ed000)
	libiconv.so.2 => ~/miniforge/lib/././libiconv.so.2 (0x00007f4acb407000)
	libcrypto.so.1.1 => ~/miniforge/lib/././libcrypto.so.1.1 (0x00007f4acb13b000)
	libcurl.so.4 => ~/miniforge/lib/././libcurl.so.4 (0x00007f4acb09e000)
	libgmp.so.10 => ~/miniforge/lib/././libgmp.so.10 (0x00007f4acaff8000)
	libpng16.so.16 => ~/miniforge/lib/././libpng16.so.16 (0x00007f4acafbf000)
	libjpeg.so.9 => ~/miniforge/lib/././libjpeg.so.9 (0x00007f4acaf81000)
	libspqr.so.2 => ~/miniforge/lib/././libspqr.so.2 (0x00007f4acaf4d000)
	libcholmod.so.3 => ~/miniforge/lib/././libcholmod.so.3 (0x00007f4acae3e000)
	libcxsparse.so.3 => ~/miniforge/lib/././libcxsparse.so.3 (0x00007f4acae09000)
	libCbcSolver.so.3 => ~/miniforge/lib/././libCbcSolver.so.3 (0x00007f4acad05000)
	libCbc.so.3 => ~/miniforge/lib/././libCbc.so.3 (0x00007f4acabe0000)
	libCgl.so.1 => ~/miniforge/lib/././libCgl.so.1 (0x00007f4acaac6000)
	libOsiClp.so.1 => ~/miniforge/lib/././libOsiClp.so.1 (0x00007f4acaa69000)
	libClpSolver.so.1 => ~/miniforge/lib/././libClpSolver.so.1 (0x00007f4aca9fd000)
	libClp.so.1 => ~/miniforge/lib/././libClp.so.1 (0x00007f4aca82e000)
	libOsi.so.1 => ~/miniforge/lib/././libOsi.so.1 (0x00007f4aca7d6000)
	libCoinUtils.so.3 => ~/miniforge/lib/././libCoinUtils.so.3 (0x00007f4aca696000)
	libipopt.so.1 => not found
	libdmumps_seq-5.2.1.so => ~/miniforge/lib/././libdmumps_seq-5.2.1.so (0x00007f4aca46e000)
	libmumps_common_seq-5.2.1.so => ~/miniforge/lib/././libmumps_common_seq-5.2.1.so (0x00007f4aca40d000)
	libpord_seq-5.2.1.so => ~/miniforge/lib/././libpord_seq-5.2.1.so (0x00007f4aca3f4000)
	libmpiseq_seq-5.2.1.so => ~/miniforge/lib/././libmpiseq_seq-5.2.1.so (0x00007f4aca3e8000)
	libesmumps-6.so => ~/miniforge/lib/././libesmumps-6.so (0x00007f4aca3e1000)
	libscotch-6.so => ~/miniforge/lib/././libscotch-6.so (0x00007f4aca33c000)
	libscotcherr-6.so => ~/miniforge/lib/././libscotcherr-6.so (0x00007f4aca335000)
	libmetis.so => ~/miniforge/lib/././libmetis.so (0x00007f4aca2c0000)
	libgfortran.so.4 => not found
	libquadmath.so.0 => ~/miniforge/lib/././libquadmath.so.0 (0x00007f4aca286000)
	libicudata.so.68 => ~/miniforge/lib/./././libicudata.so.68 (0x00007f4ac8743000)
	libnghttp2.so.14 => ~/miniforge/lib/./././libnghttp2.so.14 (0x00007f4ac871a000)
	libssh2.so.1 => ~/miniforge/lib/./././libssh2.so.1 (0x00007f4ac86d6000)
	libssl.so.1.1 => ~/miniforge/lib/./././libssl.so.1.1 (0x00007f4ac8646000)
	libgssapi_krb5.so.2 => ~/miniforge/lib/./././libgssapi_krb5.so.2 (0x00007f4ac85f3000)
	libkrb5.so.3 => ~/miniforge/lib/./././libkrb5.so.3 (0x00007f4ac851f000)
	libk5crypto.so.3 => ~/miniforge/lib/./././libk5crypto.so.3 (0x00007f4ac8503000)
	libcom_err.so.3 => ~/miniforge/lib/./././libcom_err.so.3 (0x00007f4ac84fd000)
	libamd.so.2 => ~/miniforge/lib/./././libamd.so.2 (0x00007f4ac84f0000)
	libcolamd.so.2 => ~/miniforge/lib/./././libcolamd.so.2 (0x00007f4ac84e7000)
	libsuitesparseconfig.so.5 => ~/miniforge/lib/./././libsuitesparseconfig.so.5 (0x00007f4ac84e2000)
	libccolamd.so.2 => ~/miniforge/lib/./././libccolamd.so.2 (0x00007f4ac84d4000)
	libcamd.so.2 => ~/miniforge/lib/./././libcamd.so.2 (0x00007f4ac84c4000)
	libkrb5support.so.0 => ~/miniforge/lib/././././libkrb5support.so.0 (0x00007f4ac84b5000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f4ac829e000)
```

**Comment by jschueller** [comment]
ok, it looks that the bonmin package should be updated

**Comment by vchabri** [comment]
FYI: I installed a standard miniconda3, then I used "pip install openturns" and it worked. I got the 1.17.
On the other hand, I couldn't install any package from "conda install" this morning (neither OT, nor spyder, notebook, etc.).
Again, don't know if it helps...

**Comment by jschueller** [comment]
@josephmure it should be okay now
