### ISSUE TITLE
[Debian] pyinstallcheck_SimulatedAnnealingLHS_std issue on arm64, ppc64el, s390x, powerpc, ppc64, i386

### ISSUE THREAD

**Issue by pgrt** [openturns/openturns#2048]
Hello,

While packaging version 1.18 for Debian, I noticed the following test failure on arm64, ppc64el, s390x, powerpc, ppc64, i386:

452/550 Test  #941: pyinstallcheck_SimulatedAnnealingLHS_std ...............................***Failed    1.19 sec
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/python/test/t_SimulatedAnnealingLHS_std.py", line 120, in <module>
    ott.assert_almost_equal(result.getC2(), 0.05473015652160929)
  File "/<<PKGBUILDDIR>>/debian/tmp/usr/lib/python3.10/site-packages/openturns/testing.py", line 194, in assert_almost_equal
    return _testing.assert_almost_equal(*args)
RuntimeError: Value 0.052271 is not close enough to 0.0547302 

and the following one on i386 (32-bit arch):

        Start  935: pyinstallcheck_SimulatedAnnealingLHS_std
442/532 Test  #935: pyinstallcheck_SimulatedAnnealingLHS_std ...............................***Failed    1.60 sec
Traceback (most recent call last):
  File "/home/pgt/openturns-1.18/python/test/t_SimulatedAnnealingLHS_std.py", line 120, in <module>
    ott.assert_almost_equal(result.getC2(), 0.05473015652160929)
  File "/home/pgt/openturns-1.18/debian/tmp/usr/lib/python3.10/site-packages/openturns/testing.py", line 194, in assert_almost_equal
    return _testing.assert_almost_equal(*args)
RuntimeError: Value 0.0492502 is not close enough to 0.0547302

I am unsure the only issue is linked to numerical accuracy here, which is why I am submitting this issue to you.

Thanks and cheers,

Pierre

**Comment by jschueller** [comment]
I found out that this is due to the floating-point expression contraction optimization.
One can work-around it by setting "-ffp-contract=off" in CXXFLAGS.
Not sure if it should be in our cmakelists or can be kept in the package (it's not an incorrect result, but our reference is x86_64 where such optimizations are not available)
