### ISSUE TITLE
Cannot load a PythonPointToFieldFunction from a Study

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#2066]
The save/load mechanism of PythonPointToFieldFunction is tested into `t_PointToFieldFunction_python.py`. If the script is split into two parts then the load mechanism fails if the definition of the specific OpenTURNSPythonPointToFieldFunction class is not present.

save.py:
```
import openturns as ot

mesh = ot.RegularGrid(0.0, 0.1, 11)

class FUNC(ot.OpenTURNSPythonPointToFieldFunction):

    def __init__(self):
        super(FUNC, self).__init__(2, mesh, 2)
        self.setInputDescription(['R', 'S'])
        self.setOutputDescription(['T', 'U'])
        self.mesh_ = ot.RegularGrid(0.0, 0.1, 11)

    def _exec(self, X):
        size = self.mesh_.getVerticesNumber()
        values = [ot.Point(X) * i for i in range(size)]
        return values

F = FUNC()
f1 = ot.PointToFieldFunction(F)
st = ot.Study()
fileName = 'PyNMF.xml'
st.setStorageManager(ot.XMLStorageManager(fileName))
st.add("f1", f1)
st.save()
```

load.py:
```
import openturns as ot

fileName = 'PyNMF.xml'
f1 = ot.PointToFieldFunction()
st = ot.Study()
st.setStorageManager(ot.XMLStorageManager(fileName))
st.load()
st.fillObject("f1", f1)
```

after `python save.py`, a file named PyNMF.xml is created, then `python load.py` produces:
```
Traceback (most recent call last):
  File "/home/regis/.local/lib/python3.8/site-packages/dill/_dill.py", line 327, in loads
    return load(file, ignore, **kwds)
  File "/home/regis/.local/lib/python3.8/site-packages/dill/_dill.py", line 313, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/home/regis/.local/lib/python3.8/site-packages/dill/_dill.py", line 525, in load
    obj = StockUnpickler.load(self)
  File "/home/regis/.local/lib/python3.8/site-packages/dill/_dill.py", line 515, in find_class
    return StockUnpickler.find_class(self, module, name)
AttributeError: Can't get attribute 'FUNC' on <module '__main__' from 'load.py'>
Traceback (most recent call last):
  File "load.py", line 9, in <module>
    st.fillObject("f1", f1)
  File "/home/regis/openturns-adm/build/install/lib64/python3.8/site-packages/openturns/common.py", line 757, in fillObject
    return _common.Study_fillObject(self, *args)
TypeError: InvalidArgumentException : No object with label 'f1' in study
```

**Comment by jschueller** [comment]
is the dill python module installed ? it should prevent that

**Comment by jschueller** [comment]
it works only through the PythonPointToFieldFunction ctor:

```
def F(X):
    values = [ot.Point(X) * i for i in range(11)]
    return values
f1 = ot.PythonPointToFieldFunction(2, mesh, 2, F)
```

**Comment by regislebrun** [comment]
So how can do it using a class? I have some expansive computations to capitalize between calls to the evaluation...

**Comment by jschueller** [comment]
you can still set attributes on a function:
```
def F(X):
    if hasattr(F, 'some_cache'):
        return F.some_cache
    else
        F.some_cache = [-42]
    ...
```

**Comment by regislebrun** [comment]
Let's call it a kludge...

**Comment by jschueller** [comment]
seems it works if you do this before the save script:
```
import dill
dill.settings['byref'] = True
dill.settings['recurse'] = True
```

**Comment by regislebrun** [comment]
You mean:
```
import dill
dill.settings['byref'] = True
dill.settings['recurse'] = True

import openturns as ot

mesh = ot.RegularGrid(0.0, 0.1, 11)


def FUNC(X):
    size = FUNC.mesh_.getVerticesNumber()
    values = [ot.Point(X) * i for i in range(size)]
    return values

FUNC.mesh_ = mesh

# Instance creation
f1 = ot.PythonPointToFieldFunction(2, mesh, 2, FUNC)

st = ot.Study()
fileName = 'PyNMF.xml'
st.setStorageManager(ot.XMLStorageManager(fileName))

st.add("f1", f1)

st.save()
```
because it fails too:
```
loaded f1= PointToFieldFunction :
  class=PythonPointToFieldFunction name=OpenTURNSPythonPointToFieldFunction
Traceback (most recent call last):
  File "/home/regis/openturns-adm/build/install/lib64/python3.8/site-packages/openturns/func.py", line 12476, in __call__
    Y = self._exec(pt)
  File "save.py", line 11, in FUNC
    size = FUNC.mesh_.getVerticesNumber()
NameError: name 'FUNC' is not defined
Traceback (most recent call last):
  File "load.py", line 16, in <module>
    outPt = f1(inPt)
  File "/home/regis/openturns-adm/build/install/lib64/python3.8/site-packages/openturns/func.py", line 12265, in __call__
    return _func.PointToFieldFunction___call__(self, *args)
RuntimeError: InternalException : Python exception: NameError: name 'FUNC' is not defined
```

**Comment by jschueller** [comment]
yes, that doesnt help

**Comment by jschueller** [comment]
dill has a hard time with super, use explicit version instead:
```
def __init__(self):
        ot.OpenTURNSPythonPointToFieldFunction.__init__(self, 2, mesh, 2)
```
I'm looking if there's an upstream issue
