### ISSUE TITLE
Cannot load Python objects with large attributes in a Study

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#2089]
When one tries to load a Python object (e.g. a PythonFunction) with a large attribute saved in a Study, one gets an error:
```
import openturns as ot

class FUNC(ot.OpenTURNSPythonFunction):

    def __init__(self, size):
        ot.OpenTURNSPythonFunction.__init__(self, 1, 1)
        self.data_ = ot.Normal().getSample(size)

    def _exec(self, X):
        return self.data_.computeMean() * X[0]

for size in [100000, 1000000]:
    print("size=", size)
    F = FUNC(size)

    # Instance creation
    f1 = ot.Function(F)

    st = ot.Study()
    fileName = 'PyNMF.xml.gz'
    st.setStorageManager(ot.XMLH5StorageManager(fileName, 9))
    st.add("f1", f1)
    st.save()

    print('saved f1=', f1)

    f1 = ot.Function()
    
    st = ot.Study()
    st.setStorageManager(ot.XMLH5StorageManager(fileName, 9))
    st.load()
    
    st.fillObject("f1", f1)
    print('loaded f1=', f1)
```
produces:
```
size= 100000
saved f1= class=PythonEvaluation name=FUNC
loaded f1= class=PythonEvaluation name=FUNC
size= 1000000
saved f1= class=PythonEvaluation name=FUNC
PyNMF.xml.gz:11: parser error : AttValue length too long
NAluL9s1OYq2GzHP9F/fC63hgBAEKbAyeL64r+Owp+Iduj3P57nAqtxdt8/zRS8ftO24z+rtFzwLJTnP
                                                                               ^
PyNMF.xml.gz:11: parser error : Memory allocation failed
NAluL9s1OYq2GzHP9F/fC63hgBAEKbAyeL64r+Owp+Iduj3P57nAqtxdt8/zRS8ftO24z+rtFzwLJTnP
                                                                               ^
PyNMF.xml.gz:11: parser error : attributes construct error
NAluL9s1OYq2GzHP9F/fC63hgBAEKbAyeL64r+Owp+Iduj3P57nAqtxdt8/zRS8ftO24z+rtFzwLJTnP
                                                                               ^
PyNMF.xml.gz:11: parser error : Couldn't find end of Start Tag object line 11
NAluL9s1OYq2GzHP9F/fC63hgBAEKbAyeL64r+Owp+Iduj3P57nAqtxdt8/zRS8ftO24z+rtFzwLJTnP
                                                                               ^
PyNMF.xml.gz:16: parser error : Opening and ending tag mismatch: openturns-study line 0 and object
  </object>
           ^
PyNMF.xml.gz:17: parser error : Extra content at the end of the document
  <object class="Point" id="33" size="0" StudyVisible="false" StudyLabel=""/>
  ^
Traceback (most recent call last):
  File "bug.py", line 31, in <module>
    st.load()
  File "/home/regis/openturns-adm/build/install/lib64/python3.8/site-packages/openturns/common.py", line 609, in load
    return _common.Study_load(self)
RuntimeError: XMLParserException : Error in parsing wrapper file PyNMF.xml.gz
```
It is due to the fact that the whole object (including the Sample attribute) is converted into a large string, which can be saved into an XML file but not reloaded. Ideally one would expect that these attributes will be stored into the H5 part of the Study.

**Comment by jschueller** [comment]
I guess we could store it by chunks into several Indices, with 8 bytes of the encoded string per value
