### ISSUE TITLE
Segfault with Pagmo

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#2397]
### What happened?

When I run the script t_Pagmo_std.py using master & pagmo 2.19.0 (https://github.com/esa/pagmo2/archive/refs/tags/v2.19.0.tar.gz) I get a segfault. Using gdb, the backtrace is:
```
GNU gdb (GDB) 12.1-7.mga9 (Mageia release 9)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-mageia-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...
Reading symbols from .gnu_debugdata for /usr/bin/python3.10...
(No debugging symbols found in .gnu_debugdata for /usr/bin/python3.10)
Missing separate debuginfos, use: debuginfo-install python3-3.10.11-1.mga9.x86_64
(gdb) run ../python/test/t_Pagmo_std.py
Starting program: /usr/bin/python ../python/test/t_Pagmo_std.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffed7666c0 (LWP 667011)]
[New Thread 0x7fffecf656c0 (LWP 667012)]
[New Thread 0x7fffe47646c0 (LWP 667013)]
[New Thread 0x7fffdbf636c0 (LWP 667014)]
[New Thread 0x7fffcb7626c0 (LWP 667015)]
[New Thread 0x7fffc2f616c0 (LWP 667016)]
[New Thread 0x7fffc27606c0 (LWP 667017)]
[New Thread 0x7fffb9f5f6c0 (LWP 667018)]
[New Thread 0x7fffa975e6c0 (LWP 667019)]
[New Thread 0x7fffa0f5d6c0 (LWP 667020)]
[New Thread 0x7fff9875c6c0 (LWP 667021)]
[New Thread 0x7fff8ff5b6c0 (LWP 667022)]
[New Thread 0x7fff8775a6c0 (LWP 667023)]
[New Thread 0x7fff7ef596c0 (LWP 667024)]
[New Thread 0x7fff767586c0 (LWP 667025)]
----- multi-obj -----
[New Thread 0x7fff6873d6c0 (LWP 669617)]
[New Thread 0x7fff6833c6c0 (LWP 669618)]
[New Thread 0x7fff67f3b6c0 (LWP 669619)]
[New Thread 0x7fff67b3a6c0 (LWP 669620)]
[New Thread 0x7fff677396c0 (LWP 669621)]
[New Thread 0x7fff673386c0 (LWP 669622)]
[New Thread 0x7fff667356c0 (LWP 669623)]
[New Thread 0x7fff65f336c0 (LWP 669626)]
[New Thread 0x7fff663346c0 (LWP 669627)]
[New Thread 0x7fff66f376c0 (LWP 669624)]
[New Thread 0x7fff66b366c0 (LWP 669625)]
[New Thread 0x7fff65b326c0 (LWP 669629)]
[New Thread 0x7fff657316c0 (LWP 669628)]
[New Thread 0x7fff653306c0 (LWP 669630)]
[New Thread 0x7fff6472f6c0 (LWP 669631)]
nsga2 9
nsga2 12
moead 10
moead 11
mhaco 14
mhaco 9
nspso 17
nspso 2
----- mono-obj -----
gaco [0.948126,0.895613] [1.0038]
gaco [-0.0214153,-0.0163508] [2.07154]
de [1.05228,1.11217] [1.00512]
de [0.146807,-0.000408787] [1.77617]
sade [0.981722,0.974671] [1.0122]
sade [0.181111,-0.00713378] [1.83006]
de1220 [0.978792,0.963313] [1.00324]
de1220 [0.13026,-0.0010796] [1.78902]
gwo [0.76379,0.581609] [1.05611]
gwo [0.160604,-7.67086e-06] [1.77116]
ihs [0.641845,0.501543] [1.93069]
ihs [-0.0214153,-0.0163508] [2.07154]
pso [0.932426,0.876604] [1.00973]
pso [0.202029,-0.0050864] [1.84746]
pso_gen [1.0274,1.04846] [1.00577]
pso_gen [0.173041,-0.00243085] [1.78867]
sea [0.641845,0.501543] [1.93069]
sea [-0.0214153,-0.0163508] [2.07154]
sga [0.522587,0.264845] [1.23473]
sga [0.12277,-0.0163508] [1.86827]
simulated_annealing [0.717791,0.524257] [1.0878]
simulated_annealing [0.159602,-0.00256199] [1.78486]
bee_colony [0.669667,0.449752] [1.10929]
bee_colony [0.14903,-0.00105719] [1.77829]

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007ffff0d84dac in pagmo::bfe::operator()(pagmo::problem const&, std::vector<double, std::allocator<double> > const&) const () from /usr/local/lib64/libpagmo.so.9
(gdb) bt
#0  0x00007ffff0d84dac in pagmo::bfe::operator()(pagmo::problem const&, std::vector<double, std::allocator<double> > const&) const () from /usr/local/lib64/libpagmo.so.9
#1  0x00007ffff0d20f14 in pagmo::cmaes::evolve(pagmo::population) const () from /usr/local/lib64/libpagmo.so.9
#2  0x00007ffff57a530e in pagmo::detail::algo_inner<pagmo::cmaes>::evolve (this=0xff9cb0, pop=...) at /home/regis/local/include/pagmo/algorithm.hpp:222
#3  0x00007ffff0d70c02 in pagmo::algorithm::evolve(pagmo::population const&) const () from /usr/local/lib64/libpagmo.so.9
#4  0x00007ffff579f542 in OT::Pagmo::run (this=0xc6e130) at /home/regis/openturns-dev/lib/src/Base/Optim/Pagmo.cxx:610
#5  0x00007fff6bbb9255 in _wrap_Pagmo_run (args=<optimized out>) at /home/regis/openturns-dev/build_mesh_tools/python/src/CMakeFiles/optim.dir/optim_modulePYTHON_wrap.cxx:34406
#6  0x00007ffff7d19f52 in cfunction_vectorcall_O () from /lib64/libpython3.10.so.1.0
#7  0x00007ffff7d14185 in _PyEval_EvalFrameDefault () from /lib64/libpython3.10.so.1.0
#8  0x00007ffff7d0e263 in _PyEval_Vector () from /lib64/libpython3.10.so.1.0
#9  0x00007ffff7d0f867 in _PyEval_EvalFrameDefault () from /lib64/libpython3.10.so.1.0
#10 0x00007ffff7d0e263 in _PyEval_Vector () from /lib64/libpython3.10.so.1.0
#11 0x00007ffff7d82312 in PyEval_EvalCode () from /lib64/libpython3.10.so.1.0
#12 0x00007ffff7d92133 in run_eval_code_obj () from /lib64/libpython3.10.so.1.0
#13 0x00007ffff7d8ddaa in run_mod () from /lib64/libpython3.10.so.1.0
#14 0x00007ffff7c915dc in pyrun_file () from /lib64/libpython3.10.so.1.0
#15 0x00007ffff7c90da0 in _PyRun_SimpleFileObject () from /lib64/libpython3.10.so.1.0
#16 0x00007ffff7c93b1e in _PyRun_AnyFileObject () from /lib64/libpython3.10.so.1.0
#17 0x00007ffff7d9e52a in Py_RunMain () from /lib64/libpython3.10.so.1.0
#18 0x00007ffff7d744c7 in Py_BytesMain () from /lib64/libpython3.10.so.1.0
#19 0x00007ffff7a516b7 in __libc_start_call_main () from /lib64/libc.so.6
#20 0x00007ffff7a51775 in __libc_start_main_impl () from /lib64/libc.so.6
#21 0x0000000000401061 in _start ()
```

### How to reproduce the issue?

```shell
To reproduce the issue, run t_Pagmo_std.py from the test base.
```

### Version

```
>>> import openturns as ot
>>> print(ot.__version__)
1.22dev
```

### Operating System

Linux

### Installation media

from source

**Comment by jschueller** [comment]
cannot reproduce, could you rebuild pagmo in debug mode and post the new trace ?

**Comment by regislebrun** [comment]
I compiled both OpenTURNS and Pagmo in debug mode (RelWithDebInfo) and I still encounter the same bug. Here is the gdb session:
```
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-mageia-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...
Reading symbols from .gnu_debugdata for /usr/bin/python3.10...
(No debugging symbols found in .gnu_debugdata for /usr/bin/python3.10)
Missing separate debuginfos, use: debuginfo-install python3-3.10.11-1.mga9.x86_64
(gdb) run ../python/test/t_Pagmo_std.py 
Starting program: /usr/bin/python ../python/test/t_Pagmo_std.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffed5ff6c0 (LWP 1529688)]
[New Thread 0x7fffecdfe6c0 (LWP 1529689)]
[New Thread 0x7fffe45fd6c0 (LWP 1529690)]
[New Thread 0x7fffdbdfc6c0 (LWP 1529691)]
[New Thread 0x7fffd35fb6c0 (LWP 1529692)]
[New Thread 0x7fffcadfa6c0 (LWP 1529693)]
[New Thread 0x7fffc25f96c0 (LWP 1529694)]
[New Thread 0x7fffb9df86c0 (LWP 1529695)]
[New Thread 0x7fffb15f76c0 (LWP 1529696)]
[New Thread 0x7fffa0df66c0 (LWP 1529697)]
[New Thread 0x7fff985f56c0 (LWP 1529698)]
[New Thread 0x7fff8fdf46c0 (LWP 1529699)]
[New Thread 0x7fff8f5f36c0 (LWP 1529700)]
[New Thread 0x7fff86df26c0 (LWP 1529701)]
[New Thread 0x7fff765f16c0 (LWP 1529702)]
----- multi-obj -----
[New Thread 0x7fff6873d6c0 (LWP 1529708)]
[New Thread 0x7fff63bfe6c0 (LWP 1529710)]
[New Thread 0x7fff63fff6c0 (LWP 1529709)]
[New Thread 0x7fff637fd6c0 (LWP 1529711)]
[New Thread 0x7fff633fc6c0 (LWP 1529712)]
[New Thread 0x7fff62ffb6c0 (LWP 1529713)]
[New Thread 0x7fff627f96c0 (LWP 1529714)]
[New Thread 0x7fff623f86c0 (LWP 1529717)]
[New Thread 0x7fff61ff76c0 (LWP 1529716)]
[New Thread 0x7fff61bf66c0 (LWP 1529718)]
[New Thread 0x7fff62bfa6c0 (LWP 1529715)]
[New Thread 0x7fff617f56c0 (LWP 1529719)]
[New Thread 0x7fff60ff36c0 (LWP 1529721)]
[New Thread 0x7fff613f46c0 (LWP 1529720)]
[New Thread 0x7fff60bf26c0 (LWP 1529722)]
nsga2 9
nsga2 12
moead 10
moead 11
mhaco 14
mhaco 9
nspso 17
nspso 2
----- mono-obj -----
gaco [0.948126,0.895613] [1.0038]
gaco [-0.0214153,-0.0163508] [2.07154]
de [1.05228,1.11217] [1.00512]
de [0.146807,-0.000408787] [1.77617]
sade [0.981722,0.974671] [1.0122]
sade [0.181111,-0.00713378] [1.83006]
de1220 [0.978792,0.963313] [1.00324]
de1220 [0.13026,-0.0010796] [1.78902]
gwo [0.76379,0.581609] [1.05611]
gwo [0.160604,-7.67086e-06] [1.77116]
ihs [0.641845,0.501543] [1.93069]
ihs [-0.0214153,-0.0163508] [2.07154]
pso [0.932426,0.876604] [1.00973]
pso [0.202029,-0.0050864] [1.84746]
pso_gen [1.0274,1.04846] [1.00577]
pso_gen [0.173041,-0.00243085] [1.78867]
sea [0.641845,0.501543] [1.93069]
sea [-0.0214153,-0.0163508] [2.07154]
sga [0.522587,0.264845] [1.23473]
sga [0.12277,-0.0163508] [1.86827]
simulated_annealing [0.717791,0.524257] [1.0878]
simulated_annealing [0.159602,-0.00256199] [1.78486]
bee_colony [0.669667,0.449752] [1.10929]
bee_colony [0.14903,-0.00105719] [1.77829]

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007ffff0b689bf in pagmo::bfe::operator() (this=this@entry=0x157f000, p=..., dvs=std::vector of length 160, capacity 160 = {...}) at /home/regis/deps_ot/pagmo2-2.19.0/src/bfe.cpp:97
97          auto retval((*ptr())(p, dvs));
(gdb) bt
#0  0x00007ffff0b689bf in pagmo::bfe::operator() (this=this@entry=0x157f000, p=..., dvs=std::vector of length 160, capacity 160 = {...}) at /home/regis/deps_ot/pagmo2-2.19.0/src/bfe.cpp:97
#1  0x00007ffff0b18106 in pagmo::cmaes::evolve (this=this@entry=0x157db38, pop=...) at /home/regis/deps_ot/pagmo2-2.19.0/src/algorithms/cmaes.cpp:339
#2  0x00007ffff559f0ae in pagmo::detail::algo_inner<pagmo::cmaes>::evolve (this=0x157db30, pop=...) at /home/regis/local/include/pagmo/algorithm.hpp:222
#3  0x00007ffff0b55be2 in pagmo::algorithm::evolve (this=this@entry=0x7fffffff8a90, pop=...) at /home/regis/deps_ot/pagmo2-2.19.0/src/algorithm.cpp:143
#4  0x00007ffff55992e2 in OT::Pagmo::run (this=0x1597270) at /home/regis/openturns-adm/lib/src/Base/Optim/Pagmo.cxx:610
#5  0x00007fff6c468255 in _wrap_Pagmo_run (args=<optimized out>) at /home/regis/openturns-adm/build/python/src/CMakeFiles/optim.dir/optim_modulePYTHON_wrap.cxx:34406
#6  0x00007ffff7d19f52 in cfunction_vectorcall_O () from /lib64/libpython3.10.so.1.0
#7  0x00007ffff7d14185 in _PyEval_EvalFrameDefault () from /lib64/libpython3.10.so.1.0
#8  0x00007ffff7d0e263 in _PyEval_Vector () from /lib64/libpython3.10.so.1.0
#9  0x00007ffff7d0f867 in _PyEval_EvalFrameDefault () from /lib64/libpython3.10.so.1.0
#10 0x00007ffff7d0e263 in _PyEval_Vector () from /lib64/libpython3.10.so.1.0
#11 0x00007ffff7d82312 in PyEval_EvalCode () from /lib64/libpython3.10.so.1.0
#12 0x00007ffff7d92133 in run_eval_code_obj () from /lib64/libpython3.10.so.1.0
#13 0x00007ffff7d8ddaa in run_mod () from /lib64/libpython3.10.so.1.0
#14 0x00007ffff7c915dc in pyrun_file () from /lib64/libpython3.10.so.1.0
#15 0x00007ffff7c90da0 in _PyRun_SimpleFileObject () from /lib64/libpython3.10.so.1.0
#16 0x00007ffff7c93b1e in _PyRun_AnyFileObject () from /lib64/libpython3.10.so.1.0
#17 0x00007ffff7d9e52a in Py_RunMain () from /lib64/libpython3.10.so.1.0
#18 0x00007ffff7d744c7 in Py_BytesMain () from /lib64/libpython3.10.so.1.0
#19 0x00007ffff7a516b7 in __libc_start_call_main () from /lib64/libc.so.6
#20 0x00007ffff7a51775 in __libc_start_main_impl () from /lib64/libc.so.6
#21 0x0000000000401061 in _start ()
```

**Comment by jschueller** [comment]
I installed mageia 9 and still cannot reproduce
could you post both pagmo & openturns CMakeCache.txt files ?

**Comment by regislebrun** [comment]
For OpenTURNS:
[CMakeCache.txt](https://github.com/openturns/openturns/files/12726610/CMakeCache.txt)
For pagmo:
[CMakeCache.txt](https://github.com/openturns/openturns/files/12726622/CMakeCache.txt)

**Comment by jschueller** [comment]
ok, you have user-installed openblas/swig/eigen versions, why not use the ones from system ? they seem pretty much up to date
```
# dnf search openblas
Last metadata expiration check: 2:19:29 ago on Tue 26 Sep 2023 10:50:59 AM CEST.
=============================================== Name Exactly Matched: openblas ===============================================
openblas.x86_64 : An optimized BLAS library based on GotoBLAS2
============================================== Name & Summary Matched: openblas ==============================================
lib64openblas-devel.x86_64 : Development headers and libraries for OpenBLAS
lib64openblas-static-devel.x86_64 : Static version of OpenBLAS
openblas-srpm-macros.noarch : OpenBLAS architecture macros
=================================================== Name Matched: openblas ===================================================
lib64openblas-openmp0.x86_64 : An optimized BLAS library based on GotoBLAS2, OpenMP version
lib64openblas-openmp640.x86_64 : An optimized BLAS library based on GotoBLAS2, OpenMP version
lib64openblas-openmp64_0.x86_64 : An optimized BLAS library based on GotoBLAS2, OpenMP version
lib64openblas-serial0.x86_64 : An optimized BLAS library based on GotoBLAS2, serial version
lib64openblas-serial640.x86_64 : An optimized BLAS library based on GotoBLAS2, serial version
lib64openblas-serial64_0.x86_64 : An optimized BLAS library based on GotoBLAS2, serial version
lib64openblas-threads0.x86_64 : An optimized BLAS library based on GotoBLAS2, pthreads version
lib64openblas-threads640.x86_64 : An optimized BLAS library based on GotoBLAS2, pthreads version
lib64openblas-threads64_0.x86_64 : An optimized BLAS library based on GotoBLAS2, pthreads version
# dnf search eigen
Last metadata expiration check: 2:21:01 ago on Tue 26 Sep 2023 10:50:59 AM CEST.
=============================================== Name & Summary Matched: eigen ================================================
eigen3-devel.noarch : Header files for Eigen3
eigen3-doc.noarch : This is the API documentation for Eigen3
==================================================== Name Matched: eigen =====================================================
eigen2.noarch : Lightweight C++ template library for vector and matrix math, a.k.a. linear algebra
mingw32-eigen3.noarch : MinGW lightweight C++ template library for vector and matrix math
mingw64-eigen3.noarch : MinGW lightweight C++ template library for vector and matrix math
=================================================== Summary Matched: eigen ===================================================
arpack.x86_64 : Fortran 77 subroutines for solving large scale eigenvalue problems
libspectra-devel0.noarch : C++ Library For Large Scale Eigenvalue Problems
```

**Comment by regislebrun** [comment]
I used the install script you sent me for the dependencies:
```
# blas/lapack
wget https://github.com/xianyi/OpenBLAS/releases/download/v0.3.24/OpenBLAS-0.3.24.tar.gz && tar zxf OpenBLAS-0.3.24.tar.gz && cd OpenBLAS-0.3.24 && bash quickbuild.64bit && make PREFIX=/usr/local install > /dev/null 2>&1 && ln -s /usr/local/lib/liblapack.so /usr/local/lib/libopenblas.so  && cd .. && rm -r OpenBLAS*

# hmat
curl -fsSL https://github.com/jeromerobert/hmat-oss/archive/1.9.0.tar.gz | tar xz && cd hmat-oss-1.9.0 && cmake . && make install > /dev/null 2>&1 && cd - && rm -r hmat*

# ipopt
curl -fsSL https://bitbucket.org/petsc/pkg-metis/get/v5.1.0-p10.tar.bz2 | tar xj && cd petsc-pkg-metis-* && make config shared=1 > /dev/null 2>&1 && make install > /dev/null 2>&1 && cd - && rm -r petsc*
curl -fsSL https://github.com/coin-or-tools/ThirdParty-Mumps/archive/releases/1.6.2.tar.gz | tar xz && cd ThirdParty-Mumps-releases-1.6.2 && ./get.Mumps && FFLAGS="-O2 -fallow-argument-mismatch" ./configure --prefix=/usr/local && make > /dev/null 2>&1 && make install > /dev/null 2>&1 && cd - && rm -r ThirdParty*
curl -fsSL https://github.com/coin-or/Ipopt/archive/releases/3.14.10.tar.gz | tar xz && cd Ipopt-releases-3.14.10 && ./configure --prefix=/usr/local --without-hsl --disable-java && make > /dev/null 2>&1 && make install > /dev/null 2>&1 && cd - && rm -r Ipopt*

# bonmin
curl -fsSL https://www.coin-or.org/download/source/Bonmin/Bonmin-1.8.8.tgz | tar xz && cd Bonmin-1.8.8 && ./configure --prefix=/usr/local --with-ipopt-lib="$(pkg-config --libs ipopt)" --with-ipopt-incdir="/usr/local/include/coin-or/" && make > /dev/null 2>&1 && make install > /dev/null 2>&1 && cd - && rm -r Bonmin*

# dlib
curl -fSsL https://github.com/davisking/dlib/archive/v19.24.2.tar.gz | tar xz && cd dlib-19.24.2 \
 && mkdir build && cd build && cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DDLIB_NO_GUI_SUPPORT=ON .. && make install > /dev/null 2>&1 && cd ../.. && rm -r dlib*

# cminpack
curl -fsSL https://github.com/devernay/cminpack/archive/v1.3.8.tar.gz | tar xz && cd cminpack-1.3.8 \
 && cmake -DBUILD_SHARED_LIBS=ON -DBUILD_EXAMPLES=OFF -DCMINPACK_PRECISION=d . && make install > /dev/null 2>&1 && cd - && rm -r cminpack*

# eigen
curl -fsSL https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.bz2 | tar xj && cd eigen-3.4.0 \
 && mkdir build && cd build && cmake .. && make install > /dev/null 2>&1 && cd ../.. && rm -r eigen*

# spectra
curl -fsSL https://github.com/yixuan/spectra/archive/v1.0.1.tar.gz | tar xz && cd spectra-1.0.1 && cmake . && make install > /dev/null 2>&1 && cd - && rm -r spectra*

# glog
curl -fsSL https://github.com/google/glog/archive/v0.6.0.tar.gz | tar xz && cd glog-0.6.0 && cmake -DBUILD_TESTING=OFF . && make install > /dev/null 2>&1 && cd - && rm -r glog*

# ceres
curl -fsSL https://github.com/ceres-solver/ceres-solver/archive/2.1.0.tar.gz | tar xz && cd ceres-solver-2.1.0 \
 && cmake -DBUILD_SHARED_LIBS=ON -DGFLAGS=OFF . && make install > /dev/null 2>&1 && cd - && rm -r ceres*

# boost
curl -fSsL https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.bz2 | tar xj && cd boost_1_80_0 \
 && ./bootstrap.sh --with-toolset=gcc --with-icu --with-python=/usr/local/bin/python \
 && ./b2 -q variant=release address-model=64 architecture=x86 debug-symbols=off threading=multi runtime-link=shared link=shared toolset=gcc --layout=system ${MAKEFLAGS} install --with-serialization && cd - && rm -r boost*

# nlopt
curl -fSsL https://github.com/stevengj/nlopt/archive/v2.7.1.tar.gz | tar xz && cd nlopt-2.7.1 \
 && cmake . && make install > /dev/null 2>&1 && cd - && rm -r nlopt*

# tbb
curl -fSsL https://github.com/oneapi-src/oneTBB/archive/refs/tags/v2021.9.0.tar.gz | tar xz && cd oneTBB-2021.9.0 && cmake -DTBB_TEST=OFF . && make install > /dev/null 2>&1 && cd - && rm -r oneTBB*

# pagmo
curl -fsSL https://github.com/esa/pagmo2/archive/refs/tags/v2.19.0.tar.gz | tar xz && cd pagmo2-2.19.0 && cmake -DPAGMO_WITH_EIGEN3=ON . && make install > /dev/null 2>&1 && cd - && rm -r pagmo*

# hdf5
curl -fsSL https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.12/hdf5-1.12.2/src/hdf5-1.12.2.tar.bz2 | tar xj && cd hdf5-1.12.2 && ./configure --enable-cxx --prefix=/usr/local --disable-tests --disable-tools && make > /dev/null 2>&1 && make install > /dev/null 2>&1 && cd - && rm -r hdf5*

# fftw
curl -fsSL http://www.fftw.org/fftw-3.3.10.tar.gz | tar xz && cd fftw-3.3.10 && ./configure --enable-shared --disable-static && make > /dev/null 2>&1 && make install > /dev/null 2>&1 && cd - && rm -r fftw*

# primesieve
curl -fsSL https://github.com/kimwalisch/primesieve/archive/v11.1.tar.gz | tar xz && cd primesieve-11.1 && cmake -DBUILD_STATIC_LIBS=OFF -DWITH_MULTIARCH=OFF . && make install > /dev/null 2>&1 && cd - && rm -r primesieve*
```
I installed openblas, spectra and openblas using dnf but I still have the bug.

**Comment by jschueller** [comment]
yes, but that's only for dependencies for which there is not a system package
I'll try with openblas  system package

**Comment by jschueller** [comment]
I tried with openblas system package instead of lapack and it went without problem
If I were you I would try without any user-compiled packages (remove them under /usr/local) and use system packages
especially tbb
