### ISSUE TITLE
LHSExperiment.generate() can fail

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2431]
### What happened?

The `LHSExperiment.generate()` method can fail.

The script below produces:
```
1.21
Traceback (most recent call last):
  File "script.py", line 11, in <module>
    inputSample = experiment.generate()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "python3.11/site-packages/openturns/weightedexperiment.py", line 288, in generate
    return _weightedexperiment.WeightedExperimentImplementation_generate(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: InvalidArgumentException : Points of different dimensions cannot be added (LHS dimension = 860; RHS dimension = 1856
```

### How to reproduce the issue?

```shell
import openturns as ot
print(ot.__version__)

distribution = ot.Normal(4)
experiment = ot.LHSExperiment()
experiment.setDistribution(distribution)

for sample_size in [215, 464]:
    experiment.setSize(sample_size)
    inputSample = experiment.generate()
```

### Version

1.21

### Operating System

Linux

### Installation media

conda

### Additional Context

The code does not fail when the `generate()` method is evaluated once. But it fails when evaluated a second time. The value 860 is equal to 4 * 215. The value 1856 is equal to 4 * 464. It seems that the code does not manage correctly the update of the sample size.

I inadvertently introduced the bug when creating Smolyak's quadrature. This required the `setSize` method. I did not add the appropriate unit test for LHS at that time because it is meaningless to create a Smolyak DoE based on a LHS. Still, the `setSize` makes sense and I should have checked this.

**Comment by mbaudin47** [comment]
The issue is that the code does not set `isAlreadyComputedShuffle_` to false when the size is set. A workaround is to insert:
```python
experiment.setAlwaysShuffle(True)
```
Hence the uniform random point is generated each time `generate()` is evaluated.
