### ISSUE TITLE
t_EfficientGlobalOptimization_std.py from version 1.22 failing on armel

### ISSUE THREAD

**Issue by pgrt** [openturns/openturns#2542]
### What happened?

Hello,

The test pyinstallcheck_EfficientGlobalOptimization_std fails on the armel platform with the following output :

iteration= 6
0 : [ 0.971291 0.148941 ]
1 : [ 0.762087 0.142102 ]
2 : [ 0.73044  0        ]
3 : [ 0.73886  0.300963 ]
4 : [ 1        0        ]
5 : [ 0.741021 0        ]
0 : [ -0.975684 ]
1 : [ -0.726769 ]
2 : [ -0.728417 ]
3 : [ -0.523435 ]
4 : [ -0.787077 ]
5 : [ -0.724096 ]
iteration= 1
0 : [   0.202855 -15        ]
0 : [ 18.4135 ]
Traceback (most recent call last):
  File "/home/pgt/openturns-1.22/python/test/t_EfficientGlobalOptimization_std.py", line 158, in <module>
    openturns.testing.assert_almost_equal(result.getOptimalPoint(), [0.0] * dim, 1e-7, 1e-5)
  File "/home/pgt/openturns-1.22/debian/tmp/usr/lib/python3/dist-packages/openturns/testing.py", line 174, in assert_almost_equal
    return _testing.assert_almost_equal(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Value -14.9937 is not close enough to 0

### How to reproduce the issue?

```shell
Setup a system with Debian/experimental for armel and build openturns/1.22 inside.
```

### Version

1.22

### Operating System

Linux

### Installation media

from source

**Comment by jschueller** [comment]
its working on master, maybe ecce62e
