### ISSUE TITLE
Cannot import openturns  1.21 DLL load issue

### ISSUE THREAD

**Issue by nitawa** [openturns/openturns#2556]
### What happened?

Dear developers, 
we recently moved from Python 3.6  to Python 3.9 and compiled Openturns 1.21 with MSVC 2017 .
Compilation succeeds, but unfortunately importing Openturns in a Python session fails because  _common.cp39-win_amd64.pyd cannot be imported (see trace at the end of this issue report).

I am aware of several discussions about users experiencing the same issue when running openturns wheels, but in our case, we are compiling it. 
Do you have any recommendation or patch on how to proceed here ? Shall I try a more recent version ?

Thanks for your valuable feedback.

```
import
  Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\S\SALOME-master\W64\OT\lib\site-packages\openturns\__init__.py", line 49, in <module>
    from .common import *
  File "E:\S\SALOME-master\W64\OT\lib\site-packages\openturns\common.py", line 15, in <module>
    from . import _common
ImportError: DLL load failed while importing _common: Le module spécifié est introuvable.

 import openturns
# trying E:\S\openturns.cp39-win_amd64.pyd
# trying E:\S\openturns.pyd
# trying E:\S\openturns.py
# trying E:\S\openturns.pyw
# trying E:\S\openturns.pyc
# E:\S\SALOME-master\W64\OT\lib\site-packages\openturns\__pycache__\__init__.cpython-39.pyc matches E:\S\SALOME-master\W64\OT\lib\site-packages\openturns\__init__.py
# code object from 'E:\\S\\SALOME-master\\W64\\OT\\lib\\site-packages\\openturns\\__pycache__\\__init__.cpython-39.pyc'
# trying E:\S\SALOME-master\W64\OT\lib\site-packages\openturns\common.cp39-win_amd64.pyd
# trying E:\S\SALOME-master\W64\OT\lib\site-packages\openturns\common.pyd
# trying E:\S\SALOME-master\W64\OT\lib\site-packages\openturns\common.py
# E:\S\SALOME-master\W64\OT\lib\site-packages\openturns\__pycache__\common.cpython-39.pyc matches E:\S\SALOME-master\W64\OT\lib\site-packages\openturns\common.py
# code object from 'E:\\S\\SALOME-master\\W64\\OT\\lib\\site-packages\\openturns\\__pycache__\\common.cpython-39.pyc'
# trying E:\S\SALOME-master\W64\OT\lib\site-packages\openturns\_common.cp39-win_amd64.pyd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "E:\S\SALOME-master\W64\OT\lib\site-packages\openturns\__init__.py", line 49, in <module>
    from .common import *
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "E:\S\SALOME-master\W64\OT\lib\site-packages\openturns\common.py", line 15, in <module>
    from . import _common
  File "<frozen importlib._bootstrap>", line 1058, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: DLL load failed while importing _common: Le module spécifié est introuvable.
>
```

### How to reproduce the issue?

```shell
compile on windows
```

### Version

1.21

### Operating System

Windows

### Installation media

from source

**Comment by jschueller** [comment]
dlls are missing, they have to be copied along pyd files

**Comment by jschueller** [comment]
not specific to OT: all binary modules relying on non-system dlls could face this problem, but indeed since 3.8 you cannot rely on PATH anymore which adds up
