### ISSUE TITLE
The OrthogonalProductFunctionFactory.build() method does not accept multi-indices

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2648]
### What happened?

The script below creates an orthogonal basis of 2 functions. Then the `build()` method is evaluated to create the functions in the basis, using the multi-indices. It then fails with the following error:
```
Traceback (most recent call last):
  File "/home/devel/Documents/t_OrthogonalProductFunctionFactory_std.py", line 12, in <module>
    termBasis2 = productBasis.build(index)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/devel/miniconda3/envs/ot122/lib/python3.12/site-packages/openturns/orthogonalbasis.py", line 3671, in build
    return _orthogonalbasis.OrthogonalProductFunctionFactory_build(self, index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: in method 'OrthogonalProductFunctionFactory_build', argument 2 of type 'OT::UnsignedInteger'
```
Building the function based on a single index works fine:
```
termBasis2 = productBasis.build(i)  # OK
```

### How to reproduce the issue?

```shell
#! /usr/bin/env python

import openturns as ot

enumerateFunction = ot.LinearEnumerateFunction(2)
productBasis = ot.OrthogonalProductFunctionFactory(
    [ot.HaarWaveletFactory(), ot.HaarWaveletFactory()], enumerateFunction
)

for i in range(20):
    index = enumerateFunction(i)
    termBasis2 = productBasis.build(index)  # Fails
```
```


### Version

1.22

### Operating System

unknown

### Installation media

unknown

### Additional Context

This bug was revealed while working on #

**Comment by regislebrun** [comment]
This is *not* a bug, this is the intended behaviour of a map between $\mathbb{N}$ and a sequence of functions $(f_i)_{i\in\mathbb{N}}$. What you request is an additional feature of `OrthogonalProductFunctionFactory`, which could also be added to `OrthogonalProductPolynomialFactory`.
