### ISSUE TITLE
pyinstallcheck_EfficientGlobalOptimization_std fails on armel

### ISSUE THREAD

**Issue by pgrt** [openturns/openturns#2691]
### What happened?

Hello,

While building on Debian/unstable with armel architecture, the test pyinstallcheck_EfficientGlobalOptimization_std fails. This has consistently been the case since version 1.22 of openturns.

The assertions on lines 158 and 159 of the test file fail, all others are passing. Error message is

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/python/test/t_EfficientGlobalOptimization_std.py", line 158, in <module>
    openturns.testing.assert_almost_equal(result.getOptimalPoint(), [0.0] * dim, 1e-7, 1e-5)
  File "/<<PKGBUILDDIR>>/debian/tmp/usr/lib/python3/dist-packages/openturns/testing.py", line 174, in assert_almost_equal
    return _testing.assert_almost_equal(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Value -14.9937 is not close enough to 0 

(See https://buildd.debian.org/status/fetch.php?pkg=openturns&arch=armel&ver=1.23-3&stamp=1718523265&raw=0 for more details)

Thanks a lot for the help,

Cheers,

-- 
Pierre

### How to reproduce the issue?

```shell
Just build OT in an armel container
```

### Version

1.22, 1.23

### Operating System

Linux

### Installation media

from source

**Comment by jschueller** [comment]
dup of #2542
