### ISSUE TITLE
FunctionalChaosAlgorithm.run() can fail

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2723]
### What happened?

In the next script, I create a full polynomial chaos expansion and estimate its coefficients using least squares. This produces:
```
File c:\\Users\\c61372\\AppData\\Local\\miniforge3\\envs\\myEnvironment\\Lib\\site-packages\\openturns\\metamodel.py:4075, in FunctionalChaosAlgorithm.run(self)
   4067 def run(self):
   4068     r\"\"\"
   4069     Compute the metamodel.
   4070 
   (...)
   4073     Evaluates the metamodel and stores all the results in a result structure.
   4074     \"\"\"
-> 4075     return _metamodel.FunctionalChaosAlgorithm_run(self)

RuntimeError: Error in function boost::math::gamma_q_inv<double>(double, double): Overflow Error"
```

### How to reproduce the issue?

```python
# %%
import openturns as ot
import numpy as np
import openturns.viewer as otv

print("OT Version = ", ot.__version__)

# %%
totalDegree = 1
nTrain = 25  # size of the training sample
nTest = 1000

# %%
dist_E = ot.Beta(0.9, 3.1, 2.8e7, 4.8e7)
dist_E.setDescription(["E"])
f_para = ot.LogNormalMuSigma(3.0e4, 9.0e3, 15.0e3)  # in N
dist_F = ot.ParametrizedDistribution(f_para)
dist_F.setDescription(["F"])
dist_L = ot.Uniform(250.0, 260.0)  # in cm
dist_L.setDescription(["L"])
dist_I = ot.Beta(2.5, 4, 310.0, 450.0)  # in cm^4
dist_I.setDescription(["I"])

trueDistribution = ot.ComposedDistribution([dist_E, dist_F, dist_L, dist_I])

dim_input = 4  # dimension of the input
dim_output = 1  # dimension of the output


def function_beam(X):
    E, F, L, I = X
    Y = F * (L ** 3) / (3 * E * I)
    return [Y]


g = ot.PythonFunction(dim_input, dim_output, function_beam)

# %%
ot.RandomGenerator.SetSeed(0)

# %%
inputTrain = trueDistribution.getSample(nTrain)
outputTrain = g(inputTrain)

# %%
#inputDistribution = ot.FunctionalChaosAlgorithm.BuildDistribution(inputTrain)
rMatrix = ot.CorrelationMatrix ([[ 1, -0.0418757, 0.472551, -0.197657 ], 
                            [ -0.0418757, 1, -0.0732382, 0.318959 ], 
                            [ 0.472551, -0.0732382, 1, -0.368125 ], 
                            [ -0.197657, 0.318959, -0.368125, 1 ]])
copula = ot.NormalCopula(rMatrix)
inputDistribution = ot.ComposedDistribution(
    [ot.Uniform(2.75748e+07, 4.00104e+07),
    ot.Frechet(23439, 3.80137, 4284.58),
    ot.Uniform(249.775, 260.214),
    ot.ChiSquare(365.955)
    ], copula
)
print(inputDistribution)

# %%
inputDimension = inputDistribution.getDimension()
polynomialCollection = ot.PolynomialFamilyCollection(inputDimension)
for i in range(inputDimension):
    marginal = inputDistribution.getMarginal(i)
    polynomialCollection[i] = ot.StandardDistributionPolynomialFactory(marginal)
    
enumerateFunction = ot.LinearEnumerateFunction(inputDimension)
multivariateBasis = ot.OrthogonalProductPolynomialFactory(polynomialCollection, enumerateFunction)
basisSize = enumerateFunction.getBasisSizeFromTotalDegree(totalDegree)

# %%
selectionAlgorithm = ot.PenalizedLeastSquaresAlgorithmFactory()
projectionStrategy = ot.LeastSquaresStrategy(
    inputTrain, outputTrain, selectionAlgorithm
)    
adaptiveStrategy = ot.FixedStrategy(multivariateBasis, basisSize)    
chaosAlgo = ot.FunctionalChaosAlgorithm(
    inputTrain, outputTrain, inputDistribution, adaptiveStrategy, projectionStrategy
)
chaosAlgo.run()
```

### Version

1.23

### Operating System

Windows

### Installation media

conda

**Comment by regislebrun** [comment]
What is the expected behavior when you ask for a quantile of level 1.0 for a Gamma distribution? To throw an exception or to produce NaN, Infs? The current implementation throws an exception, which is reasonable IMO. 

If you compile OT without Boost, the alternate implementation of GammaFunction::RegularizedIncompleteGammaInverse does not throw an exception, but you get:
```
OT Version =  1.24dev
ComposedDistribution(Uniform(a = 2.75748e+07, b = 4.00104e+07), Frechet(beta = 23439, alpha = 3.80137, gamma = 4284.58), Uniform(a = 249.775, b = 260.214), ChiSquare(nu = 365.955), NormalCopula(R = [[  1         -0.0418757  0.472551  -0.197657  ]
 [ -0.0418757  1         -0.0732382  0.318959  ]
 [  0.472551  -0.0732382  1         -0.368125  ]
 [ -0.197657   0.318959  -0.368125   1         ]]))
Traceback (most recent call last):
  File "/home/regis/openturns-adm/build_no_boost/../bug_2723.py", line 81, in <module>
    chaosAlgo.run()
  File "/home/regis/openturns-adm/build_no_boost/install/lib64/python3.10/site-packages/openturns/metamodel.py", line 4079, in run
    return _metamodel.FunctionalChaosAlgorithm_run(self)
TypeError: InvalidArgumentException : Error: cannot build a linear combination from an empty collection of functions.
```

Which one is the best?

**Comment by jschueller** [comment]
the non-boost variant returns nan, but it should probably be inf or the numerical limit

but even with the numerical limit I get the same error afterwards: the Psi collection of functions is empty :/
