### ISSUE TITLE
OT 1.23 fails to build against hdf5 1.14.4.3

### ISSUE THREAD

**Issue by pgrt** [openturns/openturns#2736]
### What happened?

Hello,

Currently we have hdf5/1.10.10 in Debian, and we are about to move to hdf5/1.14.4.3 currently in Debian/experimental. The test t_Study_hdf5 fails when OT is build against hdf5/1.14.4.3:

-----------------------------
terminate called after throwing an instance of 'H5::FileIException'
Aborted
-----------------------------

The gdb stack trace is:

#0  0x00007ffff5aa43ac in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff5a554f2 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff5a3e4ed in abort () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff5ca1a3d in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff5cb306a in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff5ca15e9 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff5cb32e8 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff5f46c6b in ?? () from /lib/x86_64-linux-gnu/libhdf5_serial_cpp.so.310
#8  0x00007ffff5f54296 in H5::H5Location::openDataSet(char const*, H5::DSetAccPropList const&) const () from /lib/x86_64-linux-gnu/libhdf5_serial_cpp.so.310
#9  0x00007ffff5f54314 in H5::H5Location::openDataSet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, H5::DSetAccPropList const&) const ()
   from /lib/x86_64-linux-gnu/libhdf5_serial_cpp.so.310
#10 0x00007ffff75ceac3 in OT::XMLH5StorageManagerImplementation::writeToH5<double> (this=this@entry=0x555555a63c00, dataSetName="1")
    at ./lib/src/Base/Common/XMLH5StorageManager.cxx:191
#11 0x00007ffff75cf124 in OT::XMLH5StorageManagerImplementation::addIndexedValue<double> (this=0x555555a63c00, p_obj=..., index=1, value=<optimized out>)
    at /usr/include/c++/14/bits/new_allocator.h:104
#12 0x00007ffff72245b4 in OT::Advocate::saveIndexedValue<double> (this=0x7ffffffed0d0, attributeIndex=<optimized out>, attributeValue=<optimized out>)
    at ./lib/src/Base/Common/openturns/StorageManager.hxx:363
#13 OT::AdvocateIterator<double>::operator= (value=@0x555555a63ac8: 1, this=0x7ffffffed0d0) at ./lib/src/Base/Common/openturns/StorageManager.hxx:445
#14 OT::PersistentCollection<double>::save (this=0x555555a1a0d0, adv=...) at ./lib/src/Base/Type/openturns/PersistentCollection.hxx:212
#15 OT::Point::save (this=0x555555a1a0d0, adv=...) at ./lib/src/Base/Type/Point.cxx:405
#16 0x00007ffff751debd in OT::PersistentObject::save (this=this@entry=0x555555a1a0d0, mgr=..., label="point", fromStudy=fromStudy@entry=true)
    at /usr/include/c++/14/bits/shared_ptr_base.h:1666
#17 0x00007ffff75bceaa in OT::XMLStorageManager::save (this=0x555555634060, obj=..., label="point", fromStudy=true) at ./lib/src/Base/Common/XMLStorageManager.cxx:202
#18 0x00007ffff74c3ea8 in OT::Study::save (this=this@entry=0x7fffffff9f30) at /usr/include/c++/14/bits/shared_ptr_base.h:1666
#19 0x000055555558f716 in main () at ./lib/test/t_Study_h5.cxx:68

Thanks for your help,

Cheers,

-- 
Pierre

### How to reproduce the issue?

```shell
Build OT 1.23 against hdf5 currently in debian/experimental
```

### Version

1.23

### Operating System

Linux

### Installation media

from source

**Comment by jschueller** [comment]
this is a regression in newer hdf5 versions that needs backporting this commit:
https://github.com/HDFGroup/hdf5/pull/4473

**Comment by pgrt** [comment]
Hi Julien,

Thanks a lot, following your suggestion this commit has been backported to the hdf5 package in Debian/experimental, thus voiding the issue!

Best regards,
Pierre
