### ISSUE TITLE
Vectorize the gradient functions

### ISSUE THREAD

**Issue by mdelozzo** [openturns/openturns#2741]
### What is the idea?

Vectorization speeds up function sampling, e.g.
```python
timeit("for _ in range(100): f([1])", setup="import openturns as ot; f=ot.SymbolicFunction(['x'],['x^2'])", number=10000)
4.531367600000067
timeit("f([[1]]*100)", setup="import openturns as ot; f=ot.SymbolicFunction(['x'],['x^2'])", number=10000)
0.4124439000001985
```
When I write _function_, I'm thinking in particular of metamodels obtained with the `getMetaModel` methods. In other words, I would like to sample the gradient of PCE models, Kriging models, etc.

In my case, I would need to sample gradient functions but `GradientImplementation` expects a `Point`:
```python
f.gradient([[1],[1]])
Traceback (most recent call last):
  File "C:\Users\matthias.delozzo\AppData\Local\JetBrains\PyCharm Community Edition 2023.1\plugins\python-ce\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "...\openturns\func.py", line 9547, in gradient
    return _func.Function_gradient(self, inP)
TypeError: Object passed as argument is not convertible to a Point
```

Would it be possible to vectorize the gradients?

**Comment by jschueller** [comment]
Indeed, we dont have support for that, probably because we dont have a use-case for that inside the library, what's yours ?

**Comment by mdelozzo** [comment]
In the case of gradient-based optimization under unceetainty for example, I would like to compute the gradient of an empirical estimator of  $f$ given samples of the gradient of $f$.
