### ISSUE TITLE
Error when using a ConditionedGaussianProcess with output dimension > 1

### ISSUE THREAD

**Issue by mdelozzo** [openturns/openturns#2769]
Hi,

I get an error when using `ConditionedGaussianProcess` with an output dimension other than 1.

Is this a bug or is my code wrong?

# Reproducer

```python
import openturns as ot

# 1 output >> OK
model = ot.SymbolicFunction(["x", "y"], ["cos(x) + sin(y)"])
inputSample = ot.Sample([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0], [0.5, 0.5]])
outputSample = model(inputSample)
covarianceModel = ot.SquaredExponential([1.0, 1.0])

algo = ot.KrigingAlgorithm(inputSample, outputSample, covarianceModel)
algo.run()
result = algo.getResult()
vertices = [[0.3, 0.6], [0.4, 0.8]]
mesh2D = ot.Mesh(vertices)
process = ot.ConditionedGaussianProcess(result, mesh2D)
process.getSample(3)

# 2 outputs >> KO
model = ot.SymbolicFunction(["x", "y"], ["cos(x) + sin(y)", "cos(0.5*x) + sin(y)"])
inputSample = ot.Sample([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0], [0.5, 0.5]])
outputSample = model(inputSample)
covarianceModel = ot.TensorizedCovarianceModel([ot.SquaredExponential([1.0, 1.0])] * 2)

algo = ot.KrigingAlgorithm(inputSample, outputSample, covarianceModel)
algo.run()
result = algo.getResult()
vertices = [[0.3, 0.6], [0.4, 0.8]]
mesh2D = ot.Mesh(vertices)
process = ot.ConditionedGaussianProcess(result, mesh2D)
process.getSample(3)
```
# Error
```
Traceback (most recent call last):
  File "C:\Users\matthias.delozzo\AppData\Roaming\JetBrains\PyCharmCE2024.1\scratches\scratch_9.py", line 29, in <module>
    process.getSample(3)
  File "C:\Users\matthias.delozzo\workspace\GEMSEO\gemseo\.tox\py39\lib\site-packages\openturns\randomvector.py", line 422, in getSample
    return _randomvector.ProcessImplementation_getSample(self, size)
TypeError: InvalidArgumentException : Error: the given raw data are not compatible with the dimension and size of the sample.

Process finished with exit code 1
```

# Workaround

```python
# 2 outputs
model = ot.SymbolicFunction(["x", "y"], ["cos(x) + sin(y)", "cos(0.5*x) + sin(y)"])
inputSample = ot.Sample([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0], [0.5, 0.5]])
outputSample = model(inputSample)
covarianceModel = ot.TensorizedCovarianceModel([ot.SquaredExponential([1.0, 1.0])] * 2)


algo = ot.KrigingAlgorithm(inputSample, outputSample, covarianceModel)
algo.run()
result = algo.getResult()
vertices = [[0.3, 0.6], [0.4, 0.8]]
mesh2D = ot.Mesh(vertices)
input_data = Sample(vertices)
trend_vector = array(result.getConditionalMean(input_data))
covariance_matrix = result.getConditionalCovariance(input_data)
covariance_model = UserDefinedCovarianceModel(mesh2D, covariance_matrix)
process = GaussianProcess(covariance_model, mesh2D)
process.getSample(3) + trend_vector
```

**Comment by sofianehaddad** [comment]
Thanks for reporting, locally solved
